<?php echo $this->partial('menu.phtml'); ?>

<div class="error" style="display: none;margin-top: 10px;"></div>
<div class="container">
   <div class="span-14">
      <h3>Horário das Inscrições</h3>
   </div>
   <div class="span-4">
      <a id="reload" href="#" class="no-bottom" onclick="return false;">
         <i class="icon-refresh"></i> Recarregar
      </a>
   </div>
</div>
<hr/>
<div id="bar-chart" style="width: 800px;"></div>
