<a href="<? echo $this->baseUrl('/administrador/verdetalhesevento/id_evento/'.$this->idEvento)?>">Voltar</a>

<?
  echo $this->form;
?>


<table id="compra" class="display" cellpadding="0" cellspacing="0" border="0;" >
<thead>
<tr>
	<th>Data</th>
	<th>Hora Início</th>
	<th>Hora Fim</th>
	
</tr>
</thead>
<tbody>
<? foreach ( $this->horariosEventos as $horario ) {?>
 
  <tr>

    <td><?echo $horario["data"]?></td>
    <td><? echo $horario["hora_inicio"]?></td>
    <td><? echo $horario["hora_fim"]?></td>
  </tr>
  	
  <?}
  
  ?>
</tbody>
</table>

