<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'index'));?>">Incrições</a>  
<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'buscacaravanaadministrador'));?>">Caravanas</a>  
<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'buscaatividadeadministrador'));?>">Atividades</a>
<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'relatoriosadministrador'));?>">Relatórios</a>

<br>Buscar Caravana: <input type="text" class="text" name="nome_caravana" id="nome_caravana" value="" size="50" maxlength="50" />

<table id="compra" class="display" cellpadding="0" cellspacing="0" border="0"  >
		<thead>
			<tr>
				<th>Nome</th>
				<th>Apelido</th>
				<th>Responsável</th>
				<th>Municipio</th>
				<th>Instituição</th>
				<th>Válida</th>	
				<th>Inscritos</th>	
				<th>Validar</th>
				<th>Invalidar</th>
			</tr>
		</thead>
		<tbody id="resultadoCaravana">
		</tbody>
</table>