<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'index'));?>">Incrições</a>  
<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'buscacaravanaadministrador'));?>">Caravanas</a>  
<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'buscaatividadeadministrador'));?>">Atividades</a>  
<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'relatoriosadministrador'));?>">Relatórios</a>
<div id="id">
	<input type="hidden"  name="id_encontro" id="id_encontro" value="<?=$this->idEncontro?>" />
	<br>
</div>
<br>
<label>Busca por nome:</label><input checked="checked" type="radio" id="b_nome" name="t_busca" ><label>Email:</label><input type="radio"  id="b_email" name="t_busca" ><br>
<input type="text" class="text" name="nome_pessoa" id="nome_pessoa" value="" size="50" maxlength="50" />
<table id="pessoas" class="display" cellpadding="0" cellspacing="0" border="0">
		<thead>
			<tr>
				<th>Nome</th>
				<th>Apelido</th>
				<th>Email</th>
				<th>Municipio</th>
				<th>Instituição</th>
				<th>Caravana</th>	
				<th>Status</th>
				<th>Ação</th>
			</tr>
		</thead>
		<tbody id="resultado">
		</tbody>
</table>

<table id="compra" class="display" cellpadding="0" cellspacing="0" border="0">
		<thead >
			<tr>
				<th>Nome</th>
				<th>Apelido</th>
				<th>Email</th>	
			</tr>
		</thead>
		<tbody id="resultadoCoordenacao">
		</tbody>
</table>

<table id="compra" class="display" cellpadding="0" cellspacing="0" border="0">
		<thead >
			<tr>
				<th>Nome</th>
				<th>Apelido</th>
				<th>Email</th>
			</tr>
		</thead>
		<tbody id="resultadoOrganizacao">
		</tbody>
</table>
