<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'index'));?>">Incrições</a>  
<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'buscacaravanaadministrador'));?>">Caravanas</a>  
<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'buscaatividadeadministrador'));?>">Atividades</a>
<a href="<?php echo $this->url(array('controller'=>'administrador',
'action'=>'relatoriosadministrador'));?>">Relatórios</a>