<div id="id">
	<input type="hidden"  name="id_encontro" id="id_encontro" value="<?=$this->idEncontro?>" />
	<br>
</div>
<br>
<input type="text" class="text" name="nome_pessoa" id="nome_pessoa" value="" size="50" maxlength="50" />
<table id="pessoas" class="display" cellpadding="0" cellspacing="0" border="0">
		<thead>
			<tr>
				<th>Nome</th>
				<th>Apelido</th>
				<th>Email</th>
				<th>Twitter</th>
				<th>Municipio</th>
				<th>Instituição</th>
				<th>Caravana</th>	
				<th>Ação</th>
			</tr>
		</thead>
		<tbody id="resultado">
		</tbody>
</table>