
<?php
    //$this->headLink()->appendStylesheet($this->baseUrl('css/screen.css'));
?>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate("Conference"); ?></h3>
            </div>
            <div class="list-group">
                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'encontro',
                    'action' => 'index'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-bullhorn"></i> <?php echo $this->translate("Manage Conferences"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'encontro',
                    'action' => 'criar'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-plus"></i> <?php echo $this->translate("Create Conference"); ?>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate("Users"); ?></h3>
            </div>
            <div class="list-group">
                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'config',
                    'action' => 'permissao-usuarios'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-lock"></i> <?php echo $this->translate("User permissions"); ?>
                </a>
                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'usuario',
                    'action' => 'pedidos-mudanca-email'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-exchange"></i> <?php echo $this->translate("Requests for e-mail change"); ?>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate("System"); ?></h3>
            </div>
            <div class="list-group">
                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'config',
                    'action' => 'info-sistema'
                ), 'default', true); ?>" class="list-group-item">
                    <i class="fa fa-cog"></i> <?php echo $this->translate("System Info"); ?>
                </a>
                <a href="<?php echo $this->url(array(
                        'module' => 'admin',
                        'controller' => 'config',
                        'action' => 'limpar-cache'
                    ), 'default', true); ?>" class="list-group-item">
                    <i class="fa fa-trash"></i> <?php echo $this->translate("Clean Cache"); ?>
                </a>
            </div>
        </div>
    </div>
</div>
