
<?php
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/data-tables/dataTables.bootstrap.css'));

    $this->headScript()->appendFile($this->baseUrl('js/jquery-ui-1.9.2.custom.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/data-tables/jquery.dataTables.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/data-tables/dataTables.bootstrap.js'));
    $this->headScript()->appendFile($this->baseUrl('js/admin/config/usuarios.js'));
?>

<div class="box box-solid">
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                <div class="input-group">
					<input type="text" id="termo" class="form-control input-lg"
						autofocus="autofocus"
						placeholder="<?php echo $this->translate("Search user..."); ?>"/>
					<span class="input-group-addon">
						<i class="fa fa-2x fa-search" id="loading"></i>
					</span>
				</div>
            </div>
            <div class="col-md-6">
                <span style="margin-right: 10px;">
					<i class="fa fa-search"></i>
					<?php echo $this->translate("Search by"); ?>:
				</span>
                <div class="btn-group" data-toggle="buttons">
                    <label class="btn btn-default active">
						<input type="radio" id="b_nome" name="t_busca" value="nome" checked="checked"/>
						<?php echo $this->translate("Name"); ?>
					</label>
                    <label class="btn btn-default">
						<input type="radio" id="b_email" name="t_busca" value="email"/>
						<?php echo $this->translate("E-mail"); ?>
					</label>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-body">
                <table id="users" class="table table-hover">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate("Name"); ?></th>
                            <th><?php echo $this->translate("Nickname"); ?></th>
                            <th><?php echo $this->translate("E-mail"); ?></th>
                            <th><?php echo $this->translate("Permission"); ?></th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
