
<?php
    $this->headLink()->appendStylesheet($this->baseUrl('css/tabela_sort.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/screen.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery-ui-1.8.16.custom.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery.ui.1.8.16.ie.css'));

    $this->headScript()->appendFile($this->baseUrl('js/jquery-ui-1.8.16.custom.min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/jquery.dataTables.js'));
    $this->headScript()->appendFile($this->baseUrl('js/admin/config/usuarios.js'));
?>

<?php echo $this->partial('menu.phtml'); ?>

<div id="radioset_tipo_busca">
	<i class="icon-search"></i> <?php echo $this->translate("Search by"); ?>:
	<input type="radio" id="b_nome" name="buscar_por" value="nome" checked="checked"/>
    <label for="b_nome"><?php echo $this->translate("Name"); ?></label>
	<input type="radio" id="b_email" name="buscar_por"  value="email"/>
    <label for="b_email"><?php echo $this->translate("E-mail"); ?></label>
</div>
<br/>

<div class="container">
   <div class="span-14">
      <input type="text" class="text" name="termo" id="termo" value=""
            placeholder="<?php echo $this->translate("Search user..."); ?>"
            size="50" maxlength="50" style="float: left;"/>
      <img id="loading" src="<?=$this->baseUrl('img/loading.gif') ?>"
           style="display: none; float: left;" />
   </div>
</div>
<br/>

<table class="display" cellpadding="0" cellspacing="0" border="0">
   <thead>
      <tr>
         <th><?php echo $this->translate("Name"); ?></th>
         <th><?php echo $this->translate("Nickname"); ?></th>
         <th><?php echo $this->translate("E-mail"); ?></th>
         <th><?php echo $this->translate("Permission"); ?></th>
         <th>&nbsp;</th>
      </tr>
   </thead>
   <tbody>
   </tbody>
</table>