<!DOCTYPE html>
<html>
   <head>
	   <!--<link href="/css/sigecss.css" rel="stylesheet" type="text/css"></link>-->
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>COMSOLiD+5 - SiGE</title>
		<? $this->headLink()->appendStylesheet($this->baseUrl('css/sigecss.css')); ?>
	
		<?= $this->headScript() ?>
		<?= $this->headLink() ?>
		<?= $this->headStyle() ?>
		<link rel="shortcut icon" href="<? echo $this->baseUrl('imagens/layout/favicon_sige.png');?>" type="image/x-icon" />
  	</head>
	<body>
		<div id="principal">
			<div id="info_usu">
            <?php
               $this->usuaLogado = Zend_Auth::getInstance()->getIdentity();
               if(!empty($this->usuaLogado)){ ?>
               <span>Bem-Vindo(a) :</span>
                  <a href="<?php echo $this->url(array('controller'=>'participante',
                      'action'=>'editar'), 'default');?>">
                     <span class="apelido"><?=$this->usuaLogado['apelido']?></span>
                  </a> 
               <a href="<?php echo $this->url(array('controller'=>'index',
                   'action'=>'logout'), 'default');?>">Sair</a>
				<? } ?>
			</div>
					 
			<div id="corpo">
				
				
				<div id="conteudo">
					<?=(is_object($this->menu))?$this->menu->getView():""?>
				<?//php echo  $this->render('menu.phtml')?>
					<? if (! empty($this->deprecated)): ?>
						<p style="color: red;"><?=$this->deprecated ?></p>
					<? endif; ?>
					<?php echo $this->layout()->content ?>
				</div>
			</div>
		    
			<div id="rodape">
		   		<?php echo  $this->render('rodape.phtml')?>
			</div>
	    
	    </div>
	</body>
		
	
</html>
