<div>
	<img class="fl_left"  src="<?=$this->baseUrl('imagens/layout/icn_sige.png')?>"></img>
   
	<p  class="fl_left cl_right" align="center"> 
      SIGE por <a href="http://comsolid.org" style="color: white">COMSOLiD</a> - @Copyleft <?=date('Y') ?> |
      <a href="<?=$this->url(array('controller'=>'index',
          'action' => 'sobre'), 'default', true) ?>" style="color: white">Sobre</a>
	</p>
	<a href="http://comsolid.org/" target="_blank">
      <img class="fl_right cl_right" src="<?= $this->baseUrl('imagens/layout/icn_comsolid.png') ?>" alt="COMSOLiD"/>
   </a>
</div>