<div>
	<img class="fl_left"  src="<?=$this->baseUrl('imagens/layout/icn_plixie.png')?>"></img>
	<img class="fl_left cl_right" src="<?=$this->baseUrl('imagens/layout/icn_fidias.png')?>"></img>
	
	<p  class="fl_left cl_right" align="center"> 
	SIGE by COMSOLiD - @Copyright 2011
	</p>
	
	<img class="fl_left cl_right"  src="<?=$this->baseUrl('imagens/layout/icn_sige.png')?>"></img>
	<img class="fl_right cl_right"  src="<?=$this->baseUrl('imagens/layout/icn_comsolid.png')?>"></img>
</div>