version: '2.1'

services:
  web:
    image: nginx
    ports:
      - "8080:8080" # HTTP
      - "8181:8181" # HTTPS
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/php.inc:/etc/nginx/conf.d/php.inc
      - ./docker/nginx/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
      - ./docker/nginx/vhost-https.conf:/etc/nginx/sites-enabled/vhost-https.conf
    volumes_from:
      - php
    links:
      - php
    depends_on:
      php:
        condition: service_healthy

  php:
    build: ./docker/php56
    container_name: sige-php
    volumes:
      - .:/var/www/html
      - ./certs:/etc/ssl/certs/sige
    links:
      - pg
    entrypoint:
      - /docker-sige-php-entrypoint.sh
    depends_on:
      pg:
        condition: service_healthy

  pg:
    build: ./docker/pg
    container_name: sige-pg
    ports:
      - "5434:5432"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - ./docs/INSTALACAO/ddl-schema.sql:/docker-entrypoint-initdb.d/01-ddl-schema.sql
        - ./docs/INSTALACAO/ddl-dados-iniciais.sql:/docker-entrypoint-initdb.d/02-ddl-dados-iniciais.sql
