<?php
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/data-tables/dataTables.bootstrap.css'));

    $this->headScript()->appendFile($this->baseUrl('js/jquery-ui-1.9.2.custom.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/data-tables/jquery.dataTables.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/data-tables/dataTables.bootstrap.js'));
    $this->headScript()->appendFile($this->baseUrl('/js/admin/caravana/index.js'));
?>

<div class="row">
    <div class="col-md-5 col-md-offset-3">
        <div class="box box-solid">
            <div class="box-body">
                <div class="input-group">
                    <input type="text" class="form-control input-lg" name="termo" id="termo"
                        placeholder="<?php echo $this->translate("Search caravan..."); ?>" />
                    <span class="input-group-addon">
                        <i class="fa fa-2x fa-search" id="loading"></i>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-body no-padding">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate("Name"); ?></th>
                            <th><?php echo $this->translate("Codename"); ?></th>
                            <th><?php echo $this->translate("Responsable"); ?></th>
                            <th><?php echo $this->translate("District"); ?></th>
                            <th><?php echo $this->translate("Institution"); ?></th>
                            <th><?php echo $this->translate("Valid"); ?></th>
                            <th><?php echo $this->translate("Men"); ?></th>
                            <th><?php echo $this->translate("Women"); ?></th>
                            <th style="width: 60px;">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- busca é feita via ajax -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
