<?php
    $this->headScript()->appendFile($this->baseUrl('lib/js/parsley/parsley.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/parsley/i18n/pt-br.js'));
    $this->headScript()->appendFile($this->baseUrl('js/index/definir-senha.js'));
?>

<style>
    body {
        background: url('/img/background-login.png');
    }

    .form-signin input[type="text"] {
        margin-bottom: 10px;
    }
    .form-signin input[type="password"] {
        margin-bottom: 10px;
    }

    .vertical-offset-100 {
        padding-top: 100px;
    }

    .img-responsive {
        display: block;
        max-width: 100%;
        height: auto;
        margin: auto;
    }

    .panel {
        margin-bottom: 20px;
        background-color: rgba(255, 255, 255, 0.75);
        border: 1px solid transparent;
        border-radius: 4px;
        -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
        box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
    }

    ul.parsley-errors-list {
       list-style: none;
       color: #a94442;
       margin-top: 5px;
    }
</style>

<?php
$form = $this->form;
?>

<div class="container">

    <div class="row vertical-offset-100">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row-fluid user-row">
                        <img src="<?php echo $this->baseUrl('img/banner-login.png'); ?>"
                            class="img-responsive" alt="banner"/>
                    </div>
                </div>

                <div class="panel-body">
                    <?php echo $this->flashMessages(); ?>

                    <h3 class="text-center"><?php echo $this->translate("Set new password"); ?></h3>

                    <form method="<?php echo $form->getMethod() ?>"
                        action="<?php echo $form->getAction()?>"
                        data-parsley-validate
                        id="<?php echo $form->getName()?>"
                        class="form-signin">
                        <fieldset>
                            <?php echo $form->nova_senha->renderViewHelper() ?>
                            <?php if ($form->nova_senha->hasErrors()): ?>
                            <?php foreach($form->nova_senha->getMessages() as $item): ?>
                                <p class="text-danger"><?php echo $item; ?></p>
                            <?php endforeach; ?>
                            <?php endif; ?>

                            <div class="row">
                                <div class="col-md-8">
                                    <?php echo $form->repetir_nova_senha->renderViewHelper() ?>
                                    <?php if ($form->repetir_nova_senha->hasErrors()): ?>
                                    <?php foreach($form->repetir_nova_senha->getMessages() as $item): ?>
                                        <p class="text-danger"><?php echo $item; ?></p>
                                    <?php endforeach; ?>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $form->submit->renderViewHelper() ?>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
