<?php
    $this->headScript()->appendFile($this->baseUrl('lib/js/parsley/parsley.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/parsley/i18n/pt-br.js'));
    $this->headScript()->appendFile($this->baseUrl('js/index/definir-senha.js'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/index/login.css'));

    $form = $this->form;
?>

<div class="container">
    <div class="row vertical-offset-100">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row-fluid user-row">
                        <img src="<?php echo $this->baseUrl('img/banner-login.png'); ?>"
                            class="img-responsive" alt="banner"/>
                    </div>
                </div>

                <div class="panel-body">
                    <?php echo $this->flashMessages(); ?>

                    <h3 class="text-center"><?php echo $this->translate("Set new password"); ?></h3>

                    <form method="<?php echo $form->getMethod() ?>"
                        action="<?php echo $form->getAction()?>"
                        data-parsley-validate
                        id="<?php echo $form->getName()?>"
                        class="form-signin">
                        <fieldset>
                            <?php echo $form->nova_senha->renderViewHelper() ?>
                            <?php if ($form->nova_senha->hasErrors()): ?>
                            <?php foreach($form->nova_senha->getMessages() as $item): ?>
                                <p class="text-danger"><?php echo $item; ?></p>
                            <?php endforeach; ?>
                            <?php endif; ?>

                            <div class="row">
                                <div class="col-md-8">
                                    <?php echo $form->repetir_nova_senha->renderViewHelper() ?>
                                    <?php if ($form->repetir_nova_senha->hasErrors()): ?>
                                    <?php foreach($form->repetir_nova_senha->getMessages() as $item): ?>
                                        <p class="text-danger"><?php echo $item; ?></p>
                                    <?php endforeach; ?>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $form->submit->renderViewHelper() ?>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
