<?php
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/full-pagejs/jquery.fullPage.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/time-circles/TimeCircles.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/leaflet/leaflet.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/bootstrap/social-buttons-3.css'));

    $this->headScript()->appendFile($this->baseUrl('lib/js/full-pagejs/jquery.fullPage.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/time-circles/TimeCircles.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/leaflet/leaflet.js'));
    $this->headScript()->appendFile($this->baseUrl('js/moment-with-langs.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/sprintfjs/sprintf.min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/index/index.js'));
?>

<style>
    div.section {
        padding-left: 10px;
        padding-right: 10px;
    }
    
    .navbar-trans {
        background-color:#279ddd;
        color:#fff;
    }

    .navbar-trans li>a:hover,.navbar-trans li>a:focus,.navbar-trans li.active {
        background-color:#38afef;
    }

    .navbar-trans a{
        color:#fefefe;
    }

    .navbar-trans .form-control:focus {
        border-color: #eee;
        outline: 0;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,0.075),0 0 8px rgba(100,100,100,0.6);
        box-shadow: inset 0 1px 1px rgba(0,0,0,0.075),0 0 8px rgba(100,100,100,0.6);
    }
    
    .icon-bar {
        background-color: #FFF;
    }
    
    .section {
        color: #111;
    }
    
    .section.center {
        text-align: center;
    }
    
    .section h1 {
        font-size: 6em;
        font-weight: bold;
    }
    
    .section h3 {
        font-size: 2em;
    }
    
    .section p {
        font-size: 1.2em;
        color: #333;
    }
    
    #map {
        height: 350px;
        border: 1px solid #CCC;
        border-radius: 4px;
    }
    
    #social-buttons .btn {
        margin: 10px;
    }
</style>

<!-- Fixed navbar -->
<div class="navbar navbar-trans navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand">COMSOLiD</span>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li data-menuanchor="page-0" class="active">
                    <a href="#page-0"><?php echo $this->translate("Home"); ?></a>
                </li>
                <li data-menuanchor="page-1">
                    <a href="#page-1"><?php echo $this->translate("Conference"); ?></a>
                </li>
                <li data-menuanchor="page-2">
                    <a href="#page-2"><?php echo $this->translate("Place"); ?></a>
                </li>
                <li data-menuanchor="page-3">
                    <a href="#page-3"><?php echo $this->translate("Social Network"); ?></a>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

<div id="fullpage">
    
    <div class="section center" id="section0">
        
        <div class="row">
            <div class="col-md-3 col-md-offset-2 col-sm-6">
                <h4><?php echo $this->translate("If you already participated once click on"); ?></h4>
                <a href="<?=$this->url(array(), 'login', true) ?>"
                    class="btn btn-primary btn-lg">
                    <i class="fa fa-sign-in"></i>
                    <?php echo $this->translate("Login"); ?>
                </a>
            </div>
            <div class="col-md-3 col-md-offset-2 col-sm-6">
                <h4><?php echo $this->translate("If it's your first time click on"); ?></h4>
                <a href="<?=$this->url(array(), 'participar', true) ?>"
                    class="btn btn-default btn-lg">
                    <i class="fa fa-hand-o-right"></i>
                    <?php echo $this->translate("I want to participate!"); ?>
                </a>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
                <h3 id="countdown-title"><?php echo $this->translate("It's getting closer ..."); ?></h3>
                <div id="countdown"></div>

                <div id="banner-index" style="display: none">
                    <h1><?php echo $this->translate("It started!"); ?></h1>
                </div>
                <h4><span class="label label-success" id="datetime"></span></h4>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h3><?php echo $this->translate("Learn More"); ?></h3>
                <a href="#page-1" class="btn btn-link btn-lg">
                    <i class="fa fa-caret-down fa-3x"></i>
                </a>
            </div>
        </div>
        
    </div><!-- end of #section0 -->
    
    <div class="section center" id="section1">
        <h1 id="short_name"></h1>
        <h3 id="full_name"></h3>
        
        <div class="row" id="features"></div>
    </div><!-- end of #section1 -->
    
    <div class="section center" id="section2">
        
        <div class="row">
            <div class="col-md-6">
                <h2><?php echo $this->translate("Our conference will take place at:"); ?></h2>
                <h2 id="address"></h2>
            </div>
            <div class="col-md-6">
                <div id="map"></div>
            </div>
        </div>
        
    </div><!-- end of #section2 -->
    
    <div class="section center" id="section3">
    
        <div class="row">
            <div class="col-md-12">
                <h1><?php echo $this->translate("Social Network"); ?></h1>
                <h3><?php echo $this->translate("Keep inform about our conference on our channels"); ?></h3>
            </div>
            <div class="col-md-8 col-md-offset-2" id="social-buttons"></div>
        </div>
        
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <hr>
                <a href="#page-0" class="">
                    <i class="fa fa-caret-up fa-3x"></i>
                </a>
                <h3><?php echo $this->translate("I wanna be there!"); ?></h3>
            </div>
        </div>
    
    </div><!-- end of #section3 -->
    
</div>

        
