<?php
   $this->headScript()
      ->prependFile($this->baseUrl('js/index/index.js'),'text/javascript')
      ->prependFile($this->baseUrl('js/jquery.countdown.js'),'text/javascript');
   
   $this->headLink()
           ->prependStylesheet($this->baseUrl('css/jquery.countdown.css'));
?>

<div>
	<?php echo $this->translate("If you already participated once click on"); ?>
	<a href="<?=$this->url(array(), 'login', true) ?>"
      class="no-bottom"><i class="icon-signin"></i> <?php echo $this->translate("Login"); ?></a>.
    <?php echo $this->translate("If not click on"); ?>
	<a href="<?=$this->url(array(), 'participar', true) ?>"
      class="no-bottom"><i class="icon-hand-right"></i> <?php echo $this->translate("I want to participate!"); ?></a>.
</div>

<h3><?php echo $this->translate("It's getting closer ..."); ?></h3>
<div id="countdown"></div>
<p id="note" style="text-align: center;"></p>