<?php
    $this->headScript()->appendFile($this->baseUrl('lib/js/time-circles/TimeCircles.js'));
    $this->headScript()->appendFile($this->baseUrl('js/moment-with-langs.min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/index/index.js'));

   $this->headLink()->prependStylesheet($this->baseUrl('lib/css/time-circles/TimeCircles.css'));
?>

<div>
	<?php echo $this->translate("If you already participated once click on"); ?>
	<a href="<?=$this->url(array(), 'login', true) ?>"
      class="no-bottom"><i class="icon-signin"></i> <?php echo $this->translate("Login"); ?></a>.
    <?php echo $this->translate("If not click on"); ?>
	<a href="<?=$this->url(array(), 'participar', true) ?>"
      class="no-bottom"><i class="icon-hand-right"></i> <?php echo $this->translate("I want to participate!"); ?></a>.
</div>

<h3 id="countdown-title"><?php echo $this->translate("It's getting closer ..."); ?></h3>
<div id="countdown"></div>

<div id="banner-index" style="display: none">
	<img src="/img/comsolid7-banner-sige-index.png" alt="banner" id="banner">
</div>
