<?php
    $this->headScript()->appendFile($this->baseUrl('lib/js/parsley/parsley.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/parsley/i18n/pt-br.js'));
    $this->headScript()->appendFile($this->baseUrl('js/index/login.js'));
?>

<style>
    body {
        background: url('/img/background-login.png');
    }

    .form-signin input[type="text"] {
        margin-bottom: 10px;
    }
    .form-signin input[type="password"] {
        margin-bottom: 10px;
    }

    .vertical-offset-100 {
        padding-top: 100px;
    }

    .img-responsive {
        display: block;
        max-width: 100%;
        height: auto;
        margin: auto;
    }

    .panel {
        margin-bottom: 20px;
        background-color: rgba(255, 255, 255, 0.75);
        border: 1px solid transparent;
        border-radius: 4px;
        -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
        box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
    }
</style>

<?php
$form = $this->form;
?>

<div class="container">

    <div class="row vertical-offset-100">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row-fluid user-row">
                        <img src="<?php echo $this->baseUrl('img/banner-login.png'); ?>"
                            class="img-responsive" alt="banner"/>
                    </div>
                </div>

                <div class="panel-body">
                    <?php echo $this->flashMessages(); ?>

                    <form method="<?php echo $form->getMethod() ?>"
                        action="<?php echo $form->getAction()?>"
                        data-parsley-validate
                        id="<?php echo $form->getName()?>"
                        class="form-signin">
                        <fieldset>
                            <?php echo $form->email->renderViewHelper() ?>
                            <?php if ($form->email->hasErrors()): ?>
                            <?php foreach($form->email->getMessages() as $item): ?>
                                <p class="text-danger"><?php echo $item; ?></p>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <div class="row">
                                <div class="col-md-8">
                                    <?php echo $form->senha->renderViewHelper() ?>
                                    <?php if ($form->senha->hasErrors()): ?>
                                    <?php foreach($form->senha->getMessages() as $item): ?>
                                        <p class="text-danger"><?php echo $item; ?></p>
                                    <?php endforeach; ?>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $form->submit->renderViewHelper() ?>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>

                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="btn-group">
                                <a href="<?php echo $this->url(array(), 'recuperar-senha', true);?>"
                                    class="btn btn-link">
                                    <i class="fa fa-key"></i>
                                    <?php echo $this->translate("Forgot My Password"); ?>
                                </a>
                                <button type="button" class="btn btn-link dropdown-toggle"
                                        data-toggle="dropdown" aria-expanded="false">
                                    <span class="caret"></span>
                                    <span class="sr-only">
                                        <?php echo $this->translate("More"); ?>
                                    </span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li>
                                        <a href="<?php echo $this->url(array(
                                            'controller' => 'index',
                                            'action' => 'requisitar-mudar-email'
                                        ), 'default', true) ?>">
                                            <?php echo $this->translate("Request change e-mail"); ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <a href="<?php echo $this->url(array(), 'participar', true);?>"
                                class="btn btn-link pull-right">
                                <i class="fa fa-hand-o-right"></i>
                                <?php echo $this->translate("Participate Now"); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
