
<style>
    body {
        background: url('img/background-login.png');
    }

    .form-signin input[type="text"] {
        margin-bottom: 10px;
    }
    .form-signin input[type="password"] {
        margin-bottom: 10px;
    }

    .vertical-offset-100 {
        padding-top: 100px;
    }
    
    .img-responsive {
        display: block;
        max-width: 100%;
        height: auto;
        margin: auto;
    }
    
    .panel {
        margin-bottom: 20px;
        background-color: rgba(255, 255, 255, 0.75);
        border: 1px solid transparent;
        border-radius: 4px;
        -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
        box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
    }
</style>

<?php
$form = $this->form;
?>

<div class="container">

    <div class="row vertical-offset-100">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row-fluid user-row">
                        <img src="<?php echo $this->baseUrl('img/banner-login.png'); ?>" class="img-responsive" alt="Conxole Admin"/>
                    </div>
                </div>
                
                <div class="panel-body">
                    <?php echo $this->flashMessages(); ?>
                
                    <form method="<?php echo $form->getMethod() ?>"
                        action="<?php echo $form->getAction()?>"
                        class="form-signin">
                        <fieldset>
                            <?php echo $form->email->renderViewHelper() ?>
                            <div class="row">
                                <div class="col-md-8">
                                    <?php echo $form->senha->renderViewHelper() ?>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $form->submit->renderViewHelper() ?>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
                
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-6">
                            <a href="<?php echo $this->url(array(), 'recuperar-senha', true);?>"
                                class="btn btn-link">
                                <i class="fa fa-key"></i>
                                <?php echo $this->translate("Forgot My Password"); ?>
                            </a> 
                        </div>
                        <div class="col-md-6">
                            <a href="<?php echo $this->url(array(), 'participar', true);?>"
                                class="btn btn-link pull-right">
                                <i class="fa fa-hand-o-right"></i>
                                <?php echo $this->translate("Participate Now"); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

	
	<br>
	
