<?php
$this->headScript()->appendFile($this->baseUrl('lib/js/parsley/parsley.min.js'));
$this->headScript()->appendFile($this->baseUrl('lib/js/parsley/i18n/pt-br.js'));
$this->headScript()->appendFile($this->baseUrl('js/index/requisitar-mudar-email.js'));
?>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h3><?php echo $this->translate("Request change e-mail"); ?></h3>

        <hr>
    </div>
</div>

<?php
$form = $this->form;
?>

<form method="<?php echo $form->getMethod() ?>"
    action="<?php echo $form->getAction()?>"
    data-parsley-validate
    id="<?php echo $form->getName()?>">

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <?php echo $form->email_anterior->renderLabel() ?>
            <div class="form-group">
                <?php echo $form->email_anterior->renderViewHelper() ?>
                <div class="form-errors">
                    <?php echo $form->email_anterior->renderErrors() ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <?php echo $form->novo_email->renderLabel() ?>
            <div class="form-group">
                <?php echo $form->novo_email->renderViewHelper() ?>
                <div class="form-errors">
                    <?php echo $form->novo_email->renderErrors() ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <?php echo $form->motivo->renderLabel() ?>
            <div class="form-group">
                <?php echo $form->motivo->renderViewHelper() ?>
                <div class="form-errors">
                    <?php echo $form->motivo->renderErrors() ?>
                </div>
            </div>
        </div>
    </div>

    <?php
        if (isset($form->captcha)):
        $captcha = $form->captcha->getCaptcha()->generate();
    ?>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <?php echo $form->captcha->renderLabel(); ?>
        </div>
        <div class="col-md-2 col-md-offset-3">
            <img class="img-captcha" src="/captcha/<?php echo $captcha; ?>.png" alt="captcha">
        </div>
        <div class="col-md-2">
            <input type="hidden" name="captcha[id]" value="<?php echo $captcha; ?>"
                id="captcha-id">

            <input type="text" name="captcha[input]" id="captcha-input"
            class="form-control" autocomplete="off">
        </div>
        <div class="col-md-2">
            <?php echo $form->submit->renderViewHelper(); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-5">
            <?php if ($form->captcha->hasErrors()): ?>
            <?php foreach($form->captcha->getMessages() as $item): ?>
                <p class="text-danger"><?php echo $item; ?></p>
            <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>

</form>
