
<h2>Sobre</h2>

<h3>Desenvolvedores, contribuidores e amigos</h3>
<hr/>
<div class="row">
    <div class="col-md-6">
        <h4>2014-2013</h4><hr>
        <ul class="nav">
            <li>
                Átila Camurça
                <ul>
                    <li>E-mail:
                        <a href="mailto:camurca.home@gmail.com" target="_blank">camurca.home@gmail.com</a>
                    </li>
                    <li>Twitter:
                        <a href="https://twitter.com/#!/atilacamurca" target="_blank">@atilacamurca</a>
                    </li>
                    <li>Facebook:
                        <a href="https://www.facebook.com/atilacamurca" target="_blank">atilacamurca</a>
                    </li>
                    <li>Blog:
                        <a href="http://mad3linux.org" target="_blank">MAD3 Linux</a>
                    </li>
                    <li>Formação: estudante de Ciência da Computação do IFCE Campus Maracanaú. Junto com mais dois amigos, Alberto e Shara fundou e empresa
                        <a href="http://www.fidiasoftware.com.br/sobre/">Fidias</a> que desenvolve um software de PDV chamado Pegasus Comercial.
                    </li>
                </ul>
            </li>
            <li>
                Samir Costa
                <ul>
                    <li>E-mail:
                        <a href="mailto:samirfor@gmail.com" target="_blank">samirfor@gmail.com</a>
                    </li>
                    <li>Twitter:
                        <a href="https://twitter.com/#!/samirfor" target="_blank">@samirfor</a>
                    </li>
                    <li>Facebook:
                        <a href="https://www.facebook.com/samirfor" target="_blank">samirfor</a>
                    </li>
                    <li>Blog:
                        <a href="http://mad3linux.org" target="_blank">MAD3 Linux</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>

    <div class="col-md-6">
        <h4>2012</h4><hr>
        <ul class="nav">
            <li>Átila Camurça</li>
            <li>
                Kleber Melo
                <ul>
                    <li>E-mail:
                        <a href="mailto:kleber099@gmail.com" target="_blank">kleber099@gmail.com</a>
                    </li>
                    <li>Facebook:
                        <a href="https://www.facebook.com/kleber.d.mesquita?fref=ts" target="_blank">kleber.d.mesquita</a>
                    </li>
                </ul>
            </li>
            <li>
                Darlildo Lima
                <ul>
                    <li>E-mail:
                        <a href="mailto:darlildo.cefetce@gmail.com" target="_blank">darlildo.cefetce@gmail.com</a>
                    </li>
                    <li>Facebook:
                        <a href="https://www.facebook.com/darlildo?fref=ts" target="_blank">darlildo</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

<div class="row" style="margin-top: 10px;">
    <div class="col-md-6">
        <h4>2011</h4><hr>
        <ul class="nav">
            <li>
                Prof. Robson Siqueira
                <ul>
                    <li>E-mail:
                        <a href="mailto:siqueira.robson.dasilva@gmail.com" target="_blank">siqueira.robson.dasilva@gmail.com</a>
                    </li>
                </ul>
            </li>
            <li>Kleber Melo</li>
            <li>
                Alberto Barros
                <ul>
                    <li>E-mail:
                        <a href="mailto:jalbertogod@gmail.com" target="_blank">jalbertogod@gmail.com</a>
                    </li>
                    <li>Facebook:
                        <a href="https://www.facebook.com/alberto.barros.545?fref=ts" target="_blank">alberto.barros.545</a>
                    </li>
                </ul>
            </li>
            <li>
                Ana Kézia
                <ul>
                    <li>E-mail:
                        <a href="mailto:kezia.ninha@gmail.com" target="_blank">kezia.ninha@gmail.com</a>
                    </li>
                </ul>
            </li>
            <li>
                Dêmora Bruna
                <ul>
                    <li>Facebook:
                        <a href="https://www.facebook.com/dbrunasousa?fref=ts" target="_blank">dbrunasousa</a>
                    </li>
                </ul>
            </li>
            <li>
                Michael Guimarães
                <ul>
                    <li>Facebook:
                        <a href="https://www.facebook.com/guimaraes.miweb?fref=ts" target="_blank">guimaraes.miweb</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

<h3>O Projeto</h3>
<hr/>
<div class="row">
    <div class="col-md-3">
        <h4>Código-fonte</h4>
        <p>
            <a href="https://github.com/comsolid/sige" target="_blank">
                <i class="fa fa-github"></i>
                Github
            </a>
        </p>
    </div>
    <div class="col-md-3">
        <h4>Ferramentas de desenvolvimento</h4>
        <ul class="list-unstyled">
            <li>
                <a href="http://php.net/" target="_blank">PHP</a>
            </li>
            <li>
                <a href="http://httpd.apache.org/" target="_blank">Apache HTTP Server</a>
            </li>
            <li>
                <a href="http://framework.zend.com/" target="_blank">Zend Framework</a>
            </li>
            <li>
                <a href="http://www.postgresql.org/" target="_blank">PostgreSQL</a>
            </li>
            <li>
                <a href="http://netbeans.org/" target="_blank">NetBeans IDE</a>
            </li>
            <li>
                <a href="http://git-scm.com/" target="_blank">GIT</a>
            </li>
            <li>
                <a href="http://www.linuxfoundation.org/" target="_blank">GNU/Linux</a>
            </li>
            <li>
                <a href="http://www.ubuntu.com/" target="_blank">Ubuntu</a>
            </li>
        </ul>
    </div>
    <div class="col-md-3">
        <h4>Ferramentas Web</h4>
        <ul class="list-unstyled">
            <li>
                <a href="http://jquery.com/" target="_blank">jQuery</a>
            </li>
            <li>
                <a href="http://www.datatables.net/" target="_blank">DataTables</a>
            </li>
            <li>
                <a href="http://addyosmani.github.com/jquery-ui-bootstrap/" target="_blank">jQuery UI Bootstrap</a>
            </li>
            <li>
                <a href="http://ivaynberg.github.com/select2/" target="_blank">Select2</a>
            </li>
            <li>
                <a href="http://ios-checkboxes.awardwinningfjords.com/" target="_blank">iOS Checkboxes</a>
            </li>
            <li>
                <a href="http://fortawesome.github.com/Font-Awesome/" target="_blank">Font Awesome</a>
            </li>
            <li>
                <a href="http://www.oesmith.co.uk/morris.js/index.html" target="_blank">morris.js</a>
            </li>
            <li>
                <a href="http://alertifyjs.com/" target="_blank">AlertifyJS</a>
            </li>
        </ul>
    </div>
    <div class="col-md-3">
        <ul class="list-unstyled">
            <li>
                <a href="http://raphaeljs.com/" target="_blank">Rapha&euml;l.js</a>
            </li>
            <li>
                <a href="http://code.google.com/p/sprintf/" target="_blank">sprintf</a>
            </li>
            <li>
                <a href="http://code.google.com/p/google-code-prettify/" target="_blank">google-code-prettify</a>
            </li>
            <li>
                <a href="http://slexaxton.github.io/Jed/" target="_blank">Jed</a>
            </li>
            <li>
                <a href="http://ckeditor.com/" target="_blank">CKEditor</a>
            </li>
            <li>
                <a href="http://timeago.yarp.com/" target="_blank">jQuery Timeago</a>
            </li>
            <li>
                <a href="http://alvarotrigo.com/fullPage/" target="_blank">fullPageJS</a>
            </li>
            <li>
                <a href="http://momentjs.com/" target="_blank">momentjs</a>
            </li>
            <li>
                <a href="http://git.wimbarelds.nl/TimeCircles/" target="_blank">TimeCircles</a>
            </li>
            <li>
                <a href="http://leafletjs.com/" target="_blank">Leaflet</a>
            </li>
        </ul>
    </div>
</div>
