<?php
   $this->headLink()->appendStylesheet($this->baseUrl('css/screen.css'));

   echo $this->partial('menu.phtml');
?>

<h3>Programação parcial</h3><hr/>

<?php
$data_atual = null;
if (! empty($this->lista)):
   foreach ($this->lista as $item): ?>
<div class="container">
   <div class="span-2">
      <?php $date = new Zend_Date($item['data']); ?>
      <div>
         <p><?=$date->toString('dd') ?>/<?=$date->toString('MMM') ?></p>
      </div>
   </div>
   <div class="span-18">
      <div class="acc-evento">
         <div class="header3">
            <?=$item['nome_tipo_evento'] ?>: <?=$item['nome_evento'] ?>
            <?php if (! empty($item['descricao'])) : ?>
            (<?=$item['descricao'] ?>)
            <?php endif; ?>
         </div>
         <div>
            <div>Sala <?=$item['nome_sala'] ?> de
            <?=$item['hora_inicio'] ?> - <?=$item['hora_fim'] ?></div>
            <hr/>
            <?php
            if (! empty($item['twitter'])) {
               $id = $item['twitter'];
            } else {
               $id = $item['id_pessoa'];
            }
            ?>
            <div>
               por <a href="<?=$this->url(array('id' => $id),
                    'ver', true) ?>" target="blank"><?=$item['nome'] ?></a>
               <?php if ($item['outros'] == 1): ?>
                  e outro.
               <?php elseif ($item['outros'] > 1): ?>
                  e <?=$item['outros'] ?> outros.
               <?php endif; ?>
            </div>
            <p><?=$item['resumo'] ?></p>
         </div>
      </div>
   </div>
</div>
<hr/>
<?php
   endforeach;
else:
?>
<div class="notice" style="margin-top: 10px;">
   <div class="msg-header">Atenção!</div>
   <div>Ainda não há eventos na programação. Seja o primeiro e
      <a href="<?php echo $this->url(array('controller'=>'evento',
    'action'=>'submeter'), 'default');?>"
    class="no-bottom"><i class="icon-file"></i> Submeta um trabalho</a></div>
</div>
<?php endif; ?>