<?php echo $this->partial('menu.phtml'); ?>

<div class="container">
   <div class="span-18">
      <h3>Lista de encontros</h3>
   </div>
   <div class="span-3">
      <a href="<?=
      $this->url(array(
          'module' => 'admin',
          'controller' => 'encontro',
          'action' => 'criar'), 'default', true);
?>" class="no-bottom"><i class="icon-plus"></i> Criar Encontro</a>
   </div>
</div>

<hr/>
<? foreach($this->lista as $value): ?>
<fieldset>
   <div class="container">
      <div class="span-2">
         <a href="#">#<?=$value['id_encontro'] ?></a>
      </div>
      <div class="span-14">
         <strong><?=$value['nome_encontro'] ?></strong>
      </div>
   </div><br/>
   <div class="container">
      <div class="span-10">
         de <?=$value['data_inicio'] ?> até <?=$value['data_fim'] ?>
      </div>
      <div class="span-10">
         Codenome: <?=$value['apelido_encontro'] ?>
      </div>
   </div><br/>
   <div class="container">
      <div class="span-20">
         <a href="<?php echo $this->url(array(
            'module' => 'admin',
            'controller' => 'encontro',
            'action' => 'editar',
            'id' => $value['id_encontro']), 'default', true); ?>"
            class="no-bottom">
            <i class="icon-edit"></i> Editar
         </a>&nbsp;&nbsp;&nbsp;
         <a href="<?php echo $this->url(array(
            'module' => 'admin',
            'controller' => 'encontro',
            'action' => 'editar-mensagem-email-confirmacao',
            'id' => $value['id_encontro'],
            'id_tipo_mensagem' => $this->confirmacao), 'default', true); ?>"
            class="no-bottom">
            <i class="icon-envelope-alt"></i> Mensagem e-mail confirmação
         </a>&nbsp;&nbsp;&nbsp;
         <a href="<?php echo $this->url(array(
            'module' => 'admin',
            'controller' => 'encontro',
            'action' => 'editar-mensagem-email-confirmacao',
            'id' => $value['id_encontro'],
            'id_tipo_mensagem' => $this->correcao), 'default', true); ?>"
            class="no-bottom">
            <i class="icon-envelope-alt"></i> Mensagem e-mail recuperar senha
         </a>
      </div>
   </div>
</fieldset>
<? endforeach; ?>

<hr/>

<a href="<?=$this->url(array(
    'module' => 'admin',
    'controller' => 'encontro',
    'action' => 'criar'), 'default', true);
?>" class="no-bottom"><i class="icon-plus"></i> Criar Encontro</a>