<?
   echo $this->headScript()
        ->prependFile($this->baseUrl('js/admin/horario/salvar.js'), 'text/javascript')
        ->prependFile($this->baseUrl('js/jquery.dataTables.js'))
        ->prependFile($this->baseUrl('js/jquery-1.6.2.min.js'));
   
   echo $this->headLink()
           ->appendStylesheet($this->baseUrl('css/form.css'))
           ->appendStylesheet($this->baseUrl('css/tabela_sort.css'));
?>

<a href="<?=$this->url(array('module' => 'admin',
    'controller' => 'evento',
    'action' => 'detalhes',
    'id' => $this->idEvento), 'default', true) ?>">Voltar</a>

<h2>Editar horário</h2>

<?
echo $this->form;
?>


<table class="display" cellpadding="0" cellspacing="0" border="0;" >
   <thead>
      <tr>
         <th>Data</th>
         <th>Hora Início</th>
         <th>Hora Fim</th>

      </tr>
   </thead>
   <tbody>
      <? foreach ($this->horariosEventos as $horario) { ?>

         <tr>

            <td><? echo $horario["data"] ?></td>
            <td><? echo $horario["hora_inicio"] ?></td>
            <td><? echo $horario["hora_fim"] ?></td>
         </tr>

      <? }
      ?>
   </tbody>
</table>
