<?=$this->emailInvalidos?>

<fieldset>
    
    <a title="Adicionar Caravana"  href="<? echo $this->baseUrl('caravana/add');?>"><img src="<? echo $this->baseUrl('imagens/layout/bt_adicionar.png');?>"></a>

<dl class="detalhes">
<dt id="nome_caravana-label"><label class="required" for="nome_caravana">Caravana:</label></dt>
<dd id="nome_caravana-element">
<label class="required" for="nome_caravana"><?=$this->item["apelido_caravana"];?></label></dd>
<dt id="id_municipio-label"><label class="optional" for="id_municipio">Município:</label></dt>
<dd id="id_municipio-element">
<label class="required" for="nome_caravana"><?=$this->item["nome_municipio"];?></label></dd>
<dt id="id_instituicao-label"><label class="optional" for="id_instituicao">Instituição:</label></dt>
<dd id="id_instituicao-element">
<label class="required" for="nome_caravana"><?=$this->item["apelido_instituicao"];?></label></dd>
<dt id="id_instituicao-label"><label class="optional" for="id_instituicao">Responsável:</label></dt>
<dd id="id_instituicao-element"><label ><?=$this->item["nome"];?></label></dd>
</dl>

 <?=$this->form?>
 
 <table id="compra" class="display" cellpadding="0" cellspacing="0" border="1">
	<thead>
		<TH> Participantes </TH><TH> Ação </TH>
	</thead>
	<tbody> 
	  <?foreach($this->caravanaPartici as $linha){?>
		  <tr>
		    <td><?=$linha['nome']?></td><td><a title="Remover participante dessa caravana"  href="<?php echo $this->url(array('controller'=>'caravana','action'=>'addparticipante','ex'=>$linha['id_pessoa']));?>">REMOVER</a></td>
		  </tr>
	  <?}?>
	</tbody>
</table>
</fieldset>