<a href="<?php echo $this->url(array(), 'inscricoes');
?>">Incrições</a>

<a href="<?php echo $this->url(array('controller' => 'administrador',
       'action' => 'buscacaravanaadministrador'), 'default');
?>">Caravanas</a>

<a href="<?php echo $this->url(array(
    'module' => 'admin',
    'controller' => 'evento',
    'action' => 'index'), 'default');
?>">Evento</a>

<a href="<?php echo $this->url(array('controller' => 'administrador',
       'action' => 'relatoriosadministrador'), 'default');
?>">Relatórios</a>
<br><br>