<a href="<?php echo $this->url(array(), 'inscricoes', true);
?>" class="no-bottom"><i class="icon-pencil"></i> Incrições</a>&nbsp;&nbsp;&nbsp;

<a href="<?php echo $this->url(array('controller' => 'administrador',
       'action' => 'buscacaravanaadministrador'), 'default', true);
?>" class="no-bottom"><i class="icon-plane"></i> Caravanas</a>&nbsp;&nbsp;&nbsp;

<a href="<?php echo $this->url(array(
    'module' => 'admin',
    'controller' => 'evento',
    'action' => 'index'), 'default', true);
?>" class="no-bottom"><i class="icon-bullhorn"></i> Evento</a>&nbsp;&nbsp;&nbsp;

<a href="<?php echo $this->url(array('controller' => 'administrador',
       'action' => 'relatoriosadministrador'), 'default', true);
?>" class="no-bottom"><i class="icon-bar-chart"></i> Relatórios</a>
<br><br>