<?php echo $this->partial('menu.phtml'); ?>

<input type="hidden"  name="id_encontro" id="id_encontro" value="<?=$this->idEncontro?>" />

<div id="radioset_tipo_busca">
	<i class="icon-search"></i> Buscar por:
	<input type="radio" id="b_nome" name="t_busca" value="nome" checked="checked"/><label for="b_nome">Nome</label>
	<input type="radio" id="b_email" name="t_busca"  value="email"/><label for="b_email">E-mail</label>
	<input type="radio" id="b_municipio" name="t_busca"  value="municipio"/><label for="b_municipio">Município</label>
	<input type="radio" id="b_caravana" name="t_busca"  value="caravana"/><label for="b_caravana">Caravana</label>
	<input type="radio" id="b_instituicao" name="t_busca"  value="instituicao"/><label for="b_instituicao">Instituição</label>
</div>
<br/>
<!--<label>Busca por nome:</label>
<input checked="checked" type="radio" id="b_nome" name="t_busca" ><label>Email:</label>
<input type="radio"  id="b_email" name="t_busca" >-->

<input type="text" class="text" name="nome_pessoa" id="nome_pessoa" value=""
      placeholder="Buscar participante..." size="50" maxlength="50" style="float: left;"/>
<img id="loading" src="<?=$this->baseUrl('img/loading.gif') ?>"
     style="display: none; float: left;" />

<br/><br/>
<div class="success" style="display: none;"></div>
<div class="error" style="display: none;"></div>
<table id="pessoas" class="display" cellpadding="0" cellspacing="0" border="0">
		<thead>
			<tr>
            <th style="width: 250px;">Nome</th>
				<th>Apelido</th>
				<th>E-mail</th>
				<th>Município</th>
				<th>Instituição</th>
				<th>Caravana</th>	
				<th>Status</th>
				<th>Ação</th>
			</tr>
		</thead>
		<tbody id="resultado">
		</tbody>
</table>
