<?
   $this->headScript()
      ->prependFile($this->baseUrl('js/index/index.js'),'text/javascript')
      ->prependFile($this->baseUrl('js/jquery.countdown.js'),'text/javascript')
      ->prependFile($this->baseUrl('js/jquery-1.8.3.min.js'),'text/javascript');
   
   $this->headLink()
           ->prependStylesheet($this->baseUrl('css/jquery.countdown.css'));
?>

<div>
	Se você ja participou clique em
	<a href="<?=$this->url(array(), 'login', true) ?>"
      class="no-bottom"><i class="icon-signin"></i> Entrar</a>. Se não clique em
	<a href="<?=$this->url(array(), 'participar', true) ?>"
      class="no-bottom"><i class="icon-hand-right"></i> Quero participar!</a>.
</div>

<h3>Falta pouco para o COMSOLiD 6</h3>
<div id="countdown"></div>
<p id="note" style="text-align: center;"></p>