<?php
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/select2/select2.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/select2/select2-bootstrap.css'));

    $this->headScript()->appendFile($this->baseUrl('lib/js/select2/select2.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/select2/select2_locale_pt-BR.js'));
    $this->headScript()->appendFile($this->baseUrl('js/caravana/salvar.js'));
?>

<?php echo $this->form; ?>
