<?php
	//$this->headLink()->appendStylesheet($this->baseUrl('css/tabela_sort.css'));
	//$this->headLink()->appendStylesheet($this->baseUrl('css/caravana/index.css'));

	//$this->headScript()->appendFile($this->baseUrl('js/jquery.dataTables.js'));
	//$this->headScript()->appendFile($this->baseUrl('js/caravana/index.js'));
?>

<?php if (!is_null($this->participante)): ?>
<div class="row">
	<div class="col-md-6">
		<h4>
			<i class="fa fa-plane"></i> <?php echo $this->translate("You are registered on this caravan"); ?>
		</h4>
		<hr>
		<p>
			<?php echo $this->translate("Caravan:"); ?>
			<strong><?=$this->participante['apelido_caravana'] ?></strong>
		</p>
		<p>
			<?php echo $this->translate("District:"); ?>
			<strong><?=$this->participante['nome_municipio'] ?></strong>
		</p>
		<p>
			<?php echo $this->translate("Institution:"); ?>
			<strong><?=$this->participante['apelido_instituicao'] ?></strong>
		</p>
		<p>
			<?php echo $this->translate("Responsable:"); ?>
			<strong><?=$this->participante['nome'] ?></strong>
		</p>
	</div>
	<div class="col-md-6">
		<a href="<?php echo $this->url(array('controller' => 'caravana', 'action' => 'sair'), 'default', true); ?>"
			onclick="return confirm(_('Are you sure you want to leave this caravan?'))"
			class="btn btn-danger btn-lg pull-right">
            <i class="fa fa-times"></i> <?php echo $this->translate("Leave this caravan?"); ?>
		</a>
	</div>
</div>

<?php else: ?>


	<?php if (is_null($this->caravanaResponsavel) and is_null($this->participante)): ?>
<div class="row">
	<div class="col-md-12">
	   <h3 class="text-center">
		   <?php echo $this->translate("Are you responsable for a Caravan?"); ?>
	   </h3>
	</div>
</div>

<div class="row">
	<div class="col-md-4"><hr></div>
	<div class="col-md-4">
		<a href="<?php echo $this->url(array('controller' => 'caravana', 'action' => 'criar')); ?>"
			class="btn btn-primary btn-lg btn-block">
			<i class="fa fa-plus"></i> <?php echo $this->translate("Create caravan"); ?>
		</a>
	</div>
	<div class="col-md-4"><hr></div>
</div>

	<?php else: ?>
<div class="row">
	<div class="col-md-6">
		<h3><?php echo $this->translate("You are responsable for a Caravan"); ?></h3><hr>
		<p>
			<?php echo $this->translate("Caravan:"); ?>
			<strong><?php echo $this->caravanaResponsavel["apelido_caravana"]; ?></strong>
		</p>
		<p>
			<?php echo $this->translate("District:"); ?>
			<strong><?php echo $this->caravanaResponsavel["nome_municipio"]; ?></strong>
		</p>
		<p>
			<?php echo $this->translate("Institution:"); ?>
			<strong><?php echo $this->caravanaResponsavel["apelido_instituicao"]; ?></strong>
		</p>
		<hr>
		<div class="btn-group">
			<a href="<?php echo $this->url(array(
				'controller' => 'caravana',
				'action' => 'participantes'), 'default', true); ?>"
				class="btn btn-default btn-lg">
				<i class="fa fa-plus"></i> <?php echo $this->translate("Add participants"); ?>
			</a>
			<a href="<?php echo $this->url(array(
				'controller' => 'caravana',
				'action' => 'editar'), 'default', true) ?>"
				   class="btn btn-default btn-lg">
			  <i class="fa fa-edit"></i> <?php echo $this->translate("Edit"); ?>
			</a>
		</div>
	</div>
</div>
	<?php endif; ?>
<?php endif; ?>
