<?php if (! is_null($this->participante)): ?>
<fieldset>
   <legend>
       <i class="icon-plane"></i> <?php echo $this->translate("You are registered on this caravan"); ?>
   </legend>
	<div class="acoes">
		<a href="<?php echo $this->url(array('controller' => 'caravana',
	  'action' => 'sair'), 'default', true); ?>"
      onclick="return confirm(_('Are you sure you want to leave this caravan?'))"
      class="no-bottom">
            <i class="icon-remove"></i> <?php echo $this->translate("Leave this caravan?"); ?>
		</a>
	</div>

   <dl class="detalhes">
      <dt><label>Caravana:</label></dt>
      <dd><label><?= $this->participante['apelido_caravana'] ?></label></dd>

      <dt><label>Município:</label></dt>
      <dd><label><?= $this->participante['nome_municipio'] ?></label></dd>

      <dt><label>Instituição:</label></dt>
      <dd><label><?= $this->participante['apelido_instituicao'] ?></label></dd>

      <dt><label>Responsável:</label></dt>
      <dd><label><?= $this->participante['nome'] ?></label></dd>
   </dl>
</fieldset>
<?php else: ?>

<fieldset>
   <legend><?php echo $this->translate("You are responsable for a Caravan"); ?></legend>
   <?php if (is_null($this->caravanaResponsavel) and is_null($this->participante)): ?>
      <a href="<?php echo $this->baseUrl('caravana/criar'); ?>"
         class="no-bottom" style="float: right">
			<i class="icon-plus"></i> <?php echo $this->translate("Create caravan"); ?>
		</a>
   <?php elseif (! is_null($this->caravanaResponsavel)): ?>
      <dl class="detalhes">
         <dt id="nome_caravana-label">
            <label class="required" for="nome_caravana">
                <?php echo $this->translate("Caravan:"); ?>
            </label>
         </dt>
         <dd id="nome_caravana-element">
            <label class="required" for="nome_caravana">
                <?= $this->caravanaResponsavel["apelido_caravana"]; ?>
            </label>
         </dd>
         
         <dt id="id_municipio-label">
            <label class="optional" for="id_municipio">
                <?php echo $this->translate("District:"); ?>
            </label>
         </dt>
         <dd id="id_municipio-element">
            <label class="required" for="nome_caravana">
                <?= $this->caravanaResponsavel["nome_municipio"]; ?>
            </label>
         </dd>
         
         <dt id="id_instituicao-label">
            <label class="optional" for="id_instituicao">
                <?php echo $this->translate("Institution:"); ?>
            </label>
         </dt>
         <dd id="id_instituicao-element">
            <label class="required" for="nome_caravana">
                <?= $this->caravanaResponsavel["apelido_instituicao"]; ?>
            </label>
         </dd>
         
         <dt id="id_instituicao-label">
            <label class="optional" for="id_instituicao">
                <?php echo $this->translate("Responsable:"); ?>
            </label>
         </dt>
         <dd id="id_instituicao-element">
             <label>
                <?= $this->caravanaResponsavel["nome"]; ?>
             </label>
         </dd>
      </dl>
    
      <a href="<?=$this->url(array(
                  'controller' => 'caravana',
                  'action' => 'participantes'), 'default', true)
              ?>" class="no-bottom">
           <i class="icon-plus"></i> <?php echo $this->translate("Add participants"); ?>
      </a>&nbsp;&nbsp;&nbsp;
      <a href="<?=$this->url(array('controller' => 'caravana',
               'action' => 'editar'), 'default', true) ?>"
               class="no-bottom">
          <i class="icon-edit"></i> <?php echo $this->translate("Edit"); ?>
      </a>
	<?php endif; ?>
</fieldset>
<?php endif; ?>