<?php
    //$this->headLink()->prependStylesheet($this->baseUrl('css/tabela_sort.css'));
    //$this->headLink()->prependStylesheet($this->baseUrl('css/form.css'));
    //$this->headLink()->appendStylesheet($this->baseUrl('lib/css/data-tables/dataTables.bootstrap.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/select2/select2.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/select2/select2-bootstrap.css'));

    $this->headScript()->appendFile($this->baseUrl('lib/js/select2/select2.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/select2/select2_locale_pt-BR.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/data-tables/jquery.dataTables.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/data-tables/dataTables.bootstrap.js'));
    $this->headScript()->appendFile($this->baseUrl('js/caravana/participantes.js'));
    
?>

<h3>
    <?php echo $this->translate("Add participants to caravan:"); ?>
    <strong><?php echo $this->caravana['apelido_caravana'] ?></strong>
</h3>
<hr>

<form action="<?= $this->url(array('action' => 'participantes')) ?>" method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <input type="hidden" id="sel" name="array_id_pessoas" class="form-control"/>
            </div>
        </div>
        <div class="col-md-3">
            <input type="submit" name="submit" id="submit"
            class="btn btn-primary"
            value="<?php echo $this->translate("Confirm"); ?>"/>
        </div>

    </div>
</form>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <table class="table table-striped">
            <thead>
                <th><?php echo $this->translate("Participants"); ?></th>
                <th style="width: 70px;">&nbsp;</th>
            </thead>
            <tbody> 
            <?php foreach ($this->participantes as $participante): ?>
                <tr>
                    <td><?= $participante['nome'] ?></td>
                    <td>
                        <a href="<?php echo $this->url(array(
                            'controller' => 'caravana',
                            'action' => 'deletar-participante',
                            'pessoa' => $participante['id_pessoa'],
                            'caravana' => $this->caravana['id_caravana']));
                            ?>" class="btn btn-danger"
                            onclick="return confirm(_('Are you sure you want to delete this participant from the caravan?'))">
                            <i class="fa fa-times"></i> <?php echo $this->translate("Delete"); ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
