<a href="<?php echo $this->url(array(), 'inscricoes', true);
?>" class="no-bottom"><i class="icon-pencil"></i> Incrições</a>&nbsp;&nbsp;&nbsp;

<a href="<?php echo $this->url(array('module' => 'admin',
    'controller' => 'caravana',
    'action' => 'index'), 'default', true);
?>" class="no-bottom"><i class="icon-plane"></i> Caravana</a>&nbsp;&nbsp;&nbsp;

<a href="<?php echo $this->url(array(
    'module' => 'admin',
    'controller' => 'evento',
    'action' => 'index'), 'default', true);
?>" class="no-bottom"><i class="icon-star"></i> Evento</a>&nbsp;&nbsp;&nbsp;

<a href="<?php echo $this->url(array(
    'module' => 'admin',
    'controller' => 'relatorios',
    'action' => 'index'), 'default', true);
?>" class="no-bottom"><i class="icon-bar-chart"></i> Relatórios</a>&nbsp;&nbsp;&nbsp;
<a href="<?php echo $this->url(array(
    'module' => 'admin',
    'controller' => 'config',
    'action' => 'index'), 'default', true);
?>" class="no-bottom"><i class="icon-cogs"></i> Configurações</a>
<br><br>