 <?php echo $this->headScript() ?> 
 <div id="id">
 <input type="hidden"  name="idEncontro" id="idEncontro" value="<?=$this->idEncontro?>" />
 <input type="radio" class="radio" name="data_evento" id="data_evento" value="todas" checked="checked" /><label>Todos</label><br>
<? foreach ( $this->listaEvento as $evento ) {foreach ( $evento  as $data_submissao ) {?>
<input type="radio" class="radio"  name="data_evento" id="data_evento"  value="<?=str_replace('/','-',$data_submissao)?>" /><label><?=$data_submissao?></label><br>
<? }}
?>
</div>
 <input type="radio" class="radio" name="tipo_evento" id="tipo_evento" value="0" checked="checked" /><label>Todos</label><br>
<? foreach ( $this->tipoEvento as $tipoEvento ) {?>
       <input type="radio" class="radio"  name="tipo_evento" id="tipo_evento" value="<?=$tipoEvento->id_tipo_evento?>" /><label><?=$tipoEvento->nome_tipo_evento?></label><br>

<?}
?>
<input type="text" class="text" name="nome_evento" id="nome_evento" value="" size="50" maxlength="50" />

<table>
		<thead >
			<tr>
				<th >Tipo Evento</th>
				<th  >Descrição</th>
				<th >Dia</th>
				<th >Horário Início</th>
				<th >Horário Fim</th>
				<th ></th>	
			</tr>
		</thead>
		<tbody id="resultado">
		</tbody>
</table>
