<?php
$this->headLink()->prependStylesheet($this->baseUrl('css/screen.css'));
$this->headLink()->prependStylesheet($this->baseUrl('css/form-evento.css'));
$this->headLink()->prependStylesheet($this->baseUrl('css/font-awesome.min.css'));
$this->headLink()->prependStylesheet($this->baseUrl('css/font-awesome-ie7.min.css'));
?>
<fieldset>
   <div class="container">
      <div class="span-1">
         Data:
      </div>
      <div class="span-4">
         <?= $this->evento['data'] ?>
      </div>
      <div class="span-2">
         Horário:
      </div>
      <div class="span-4">
         <?= $this->evento['hora_inicio'] ?> - <?= $this->evento['hora_fim'] ?>
      </div>
   </div>
   <div class="container">
      <div class="span-10">
         Você irá desmarcar interesse em: <?= $this->evento['nome_evento'] ?>. Tem certeza?
      </div>
   </div>
   <br/>
   <div class="container">
      <div class="span-10">
         <form action="<?=$this->url(array('action' => 'desfazer-interesse')) ?>" method="post">
            <input type="hidden" name="id" value="<?=$this->evento['evento'] ?>" />
            <dl class="zend_form">
               <input type="submit" name="cancelar" id="cancelar" value="cancelar" class="submitCancelar">
               <input type="submit" name="del" id="del" value="confimar"/>
            </dl>
         </form>
      </div>
   </div>
</fieldset>