<div class="container">
   <div class="span-14" id="radioset_data">
      <i class="icon-calendar"></i>
      <input type="radio" name="data_evento" class="data_evento"
             id="radio_data_todos" value="todas" checked="checked" />
      <label for="radio_data_todos">Todos</label>
      <? foreach ($this->diasEncontro as $value): ?>
      <input type="radio" name="data_evento" class="data_evento" id="radio_<?= $value['data'] ?>"
                value="<?= str_replace('/', '-', $value['data']) ?>" />
      <label for="radio_<?= $value['data'] ?>"><?= $value['data'] ?></label>
      <? endforeach; ?>
   </div>
</div><br/>
<div class="container">
   <div class="span-14" id="radioset_tipo">
      <i class="icon-star"></i>
      <input type="radio" name="tipo_evento" class="tipo_evento" id="radio_tipo_todos"
             value="0" checked="checked" /><label for="radio_tipo_todos">Todos</label>
      <? foreach ($this->tipoEvento as $tipoEvento): ?>
      <input type="radio" name="tipo_evento" class="tipo_evento"
                id="radio_<?= $tipoEvento->id_tipo_evento ?>"
                value="<?= $tipoEvento->id_tipo_evento ?>" />
      <label for="radio_<?= $tipoEvento->id_tipo_evento ?>"><?= $tipoEvento->nome_tipo_evento ?></label>
      <? endforeach; ?>
   </div>
</div>
<br>
<input type="text" class="text" name="termo" id="termo"
       value="" size="50" maxlength="50" placeholder="Buscar evento..." style="float: left;" />
<img id="loading" src="<?=$this->baseUrl('img/loading.gif') ?>"
     style="display: none; float: left;" />
<br><br>
<div class="success" style="display: none;"></div>
<div class="error" style="display: none;"></div>

<fieldset>
   <legend>Interesse em Eventos</legend>
   <table class="display" cellpadding="0" cellspacing="0" border="0"  >
      <thead>
         <tr>
            <th>Evento</th>
            <th>Descrição</th>
            <th>Dia</th>
            <th>Horário</th>
            <th>Ação</th>
         </tr>
      </thead>
      <tbody id="resultado">
      </tbody>
   </table>
</fieldset>

<div class="notice">
   <p><strong>Atenção!</strong> Marcar interesse numa palestra não garante sua vaga.
      Então chegue cedo.<br/>Marcar eventos é apenas uma forma de organizar melhor os locais dependendo da demanda.</p>
</div>