
<? if (!empty($this->evento)): ?>

<?
$config = new Zend_Config_Ini(APPLICATION_PATH . '/configs/application.ini', 'staging');
/* meta tags para twitter */
$this->headMeta()->setName('twitter:card', 'summary');
$this->headMeta()->setName('twitter:description', "{$this->evento['resumo']}");
$this->headMeta()->setName('twitter:site', "@{$config->twitter->username}");
$this->headMeta()->setName('twitter:title', "{$this->evento['nome_evento']}");
$this->headMeta()->setName('twitter:url', "{$this->serverUrl()}{$this->url(array('id' => $this->evento['id_evento']),
              'ver_evento', true)}");
?>

   <div id="fb-root"></div>
   <script>(function(d, s, id) {
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) return;
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=336256479809348";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));</script>

   <div class="container">
      <div class="span-13">
         <h3><?= $this->evento['nome_tipo_evento'] ?>:
            <strong><?= $this->evento['nome_evento'] ?></strong>
         </h3>
      </div>
      <div class="span-social">
         <!-- twitter button -->
         <a href="https://twitter.com/share" class="twitter-share-button"
            data-url="<?=$this->serverUrl() . $this->url(array('id' => $this->evento['id_evento']),
              'ver_evento', true) ?>"
              data-text="<?= $this->evento['nome_evento'] ?> por <?= $this->evento['nome'] ?>"
              data-via="<?=$config->twitter->username ?>"
              data-lang="pt" data-hashtags="<?=$config->twitter->hashtags ?>">Tweetar</a>
         <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>
      <div class="span-social">   
         <!-- facebook button -->
         <div class="fb-like" data-href="<?=$this->serverUrl() . $this->url(array('id' => $this->evento['id_evento']),
              'ver_evento', true) ?>" data-send="false" data-layout="button_count"
              data-width="450" data-show-faces="false"></div>
      </div>
      <div class="span-social">
         <!-- Place this tag in your head or just before your close body tag. -->
         <script type="text/javascript" src="https://apis.google.com/js/plusone.js">
           {lang: 'pt-BR'}
         </script>

         <!-- Place this tag where you want the +1 button to render. -->
         <div class="g-plusone" data-size="medium" data-href="<?=$this->serverUrl() . $this->url(array('id' => $this->evento['id_evento']),
              'ver_evento', true) ?>"></div>
      </div>
      <hr/>
   </div>

   <div class="container">
      <div class="span-12">
         Palestrante:
         <?= $this->evento['nome'] ?>
      </div>
   </div>

   <br/>

   <div class="container">
      <div class="span-2">
         Submissão:
      </div>
      <div class="span-6">
         <? $date = new Zend_Date($this->evento['data_submissao']); ?>
         <abbr class="timeago" title="<?= $this->evento['data_submissao'] ?>">
            <?=$date->toString("dd 'de' MMMM 'de' y") ?>
         </abbr>
      </div>
      <div class="span-1">
         Nível:
      </div>
      <div class="span-4">
         <?= $this->evento['descricao_dificuldade_evento'] ?>
      </div>
   </div>

   <br/>

   <div class="container">
      <div class="span-20 prepend-2" id="tabs">
         <ul>
            <li><a href="#tab-1">Resumo</a></li>
            <li><a href="#tab-2">Outros Palestrantes</a></li>
            <li><a href="#tab-3">Perfil</a></li>
            <li><a href="#tab-4">Bio</a></li>
            <li><a href="#tab-5">Tags</a></li>
         </ul>
         <div id="tab-1">
            <?= $this->evento['resumo'] ?>
         </div>
         <div id="tab-2">
            <ul>
            <? if (! empty($this->outros)):
                  foreach ($this->outros as $outro): ?>
               <?
               $url = "/u/";
               $url .= (empty($outro['twitter']) ? $outro['id_pessoa'] : $outro['twitter']);
               ?>
               <li><a href="<?=$url ?>" title="<?=$outro['apelido'] ?>"
                      target="_blank"><?=$outro['nome'] ?></a></li>
            <?    endforeach;
               endif; ?>
            </ul>
         </div>
         <div id="tab-3">
            <?= $this->evento['perfil_minimo'] ?>
         </div>
         <div id="tab-4">
            <?= $this->evento['bio'] ?>
         </div>
         <div id="tab-5" class="select2-container select2-container-multi" style="width: 450px;">
            <ul class="select2-choices">
            <? if (! empty($this->tags)):
                  foreach ($this->tags as $tag): ?>
               <li class="select2-search-choice select2-locked">
                  <a><?=$tag['descricao'] ?></a>
               </li>
            <?    endforeach;
               endif; ?>
            </ul>
         </div>
      </div>
   </div>
   <br/><hr/>
   
   <div id="disqus_thread"></div>
   <script type="text/javascript">
       /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
       var disqus_shortname = 'comsolid';
       var disqus_title = '<?= $this->evento['nome_evento'] ?>';
       var disqus_url = '<?= $this->serverUrl() . $this->url(array('id' => $this->evento['id_evento']), 'ver_evento', true) ?>';

       /* * * DON'T EDIT BELOW THIS LINE * * */
       (function() {
           var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
           dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
           (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
       })();
   </script>
   <noscript>Por favor, habilite o JavaScript para ver os <a href="http://disqus.com/?ref_noscript">comentários do Disqus.</a></noscript>
   <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

<? endif; ?>

