
<?php echo $this->partial('menu.phtml'); ?>

<h3>Criar Encontro</h3><hr/>
<?php
   $this->headScript()
        ->prependFile($this->baseUrl('js/admin/encontro/salvar.js'), 'text/javascript')
        ->prependFile($this->baseUrl('js/jquery-ui-1.8.16.custom.min.js'), 'text/javascript')
        ->prependFile($this->baseUrl('js/jquery-1.8.3.min.js'));
   
   $this->headLink()
           ->appendStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery.ui.1.8.16.ie.css'))
           ->appendStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery-ui-1.8.16.custom.css'))
           ->appendStylesheet($this->baseUrl('css/screen.css'))
           ->appendStylesheet($this->baseUrl('css/form-evento.css'));

   echo $this->form;
?>
