
<h3><?php echo $this->title; ?></h3><hr/>
<div class="notice" style="margin-top: 10px;">
    <strong><?php echo $this->translate("Attention!"); ?></strong>
    <?php echo $this->translate("Some features of the message"); ?>:
    <ul>
        <li><?php echo $this->translate("The message can be written in HTML."); ?></li>
        <li><?php echo $this->translate("The message must contain some attributes "
                . "that will be replaced in the e-mail. They are:"); ?>
            <ul>
                <li><code>{nome}</code></li>
                <li><code>{email}</code></li>
                <li><code>{senha}</code></li>
                <li><code>{href_link}</code></li>
            </ul>
        </li>
        <li>
            <?php echo $this->translate("Is not necessary write headers, write only the content of the"); ?>
            <code>&lt;body&gt;</code>.</li>
        <li>
            <?php echo $this->translate("Is not possible to import Cascading Style Sheets (CSS) or Javascript files, the e-mail servers themselves will block them. To use CSS use the HTML attribute"); ?>
            <code>style</code>.
        </li>
    </ul>
</div>
<?php
   $this->headScript()
        ->prependFile($this->baseUrl('js/admin/encontro/salvar.js'), 'text/javascript')
        ->prependFile($this->baseUrl('js/jquery-ui-1.8.16.custom.min.js'), 'text/javascript')
        ->prependFile($this->baseUrl('js/jquery-1.8.3.min.js'));
   
   $this->headLink()
           ->appendStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery.ui.1.8.16.ie.css'))
           ->appendStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery-ui-1.8.16.custom.css'))
           ->appendStylesheet($this->baseUrl('css/screen.css'))
           ->appendStylesheet($this->baseUrl('css/form-evento.css'));
   
   echo $this->form;

?>
