<?php
    $this->headScript()->prependFile($this->baseUrl('lib/js/pdf.js/pdf.js'));
    $this->headScript()->prependFile($this->baseUrl('js/admin/encontro/editar-mensagem-certificado.js'));
?>

<style media="screen">
    #the-canvas {
        border: 1px solid #aaaaaa;
        width: 1088px;
        margin: 0px auto;
        display: block;
    }
</style>

<?php
$form = $this->form;
?>

<div class="row">
    <div class="col-md-6">
        <div class="box box-solid">
            <div class="box-body">
                <form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
                    <div class="row">
                        <div class="col-md-12">
                            <?php echo $form->mensagem->renderLabel() ?>
                            <div class="form-group">
                                <?php echo $form->mensagem->renderViewHelper() ?>
                                <div class="form-errors">
                                    <?php echo $form->mensagem->renderErrors() ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <?php echo $form->tipo_mensagem_certificado->renderViewHelper() ?>
                    <?php echo $form->id_encontro->renderViewHelper() ?>

                    <hr>

                    <div class="row">
                        <div class="col-md-12">
                            <a href="<?=$this->url(array('module' => 'admin',
                                'controller' => 'encontro',
                                'action' => 'index'), 'default', true) ?>"
                                class="btn btn-default">
                                <i class="fa fa-chevron-left"></i> <?php echo $this->translate("Back"); ?>
                            </a>

                            <?php echo $form->submit->renderViewHelper() ?>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="alert alert-warning">
            <strong>Atenção!</strong> Algumas características da mensagem:
            <ul>
                <li>
                    A mensagem abaixo <b>NÃO</b> pode ser escrita em HTML e nem importar
                    folhas de estilo (css) ou arquivos javascript (js).
                </li>
                <li><?php echo $this->translate("The message must contain some attributes "
                            . "that will be replaced in the certificate. They are:"); ?>
                    <ul>
                        <?php foreach ($this->options as $option): ?>
                            <li><code><?php echo $option ?></code></li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title"><?php echo $this->translate("Certificate Preview"); ?></h3>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <input type="hidden" id="pdf-data" value="<?php echo base64_encode($this->pdf); ?>"/>

                <canvas id="the-canvas"></canvas>
            </div>
        </div>
    </div>
</div>
