<h3>Editar mensagem confirmação e-mail</h3><hr/>
<div class="notice" style="margin-top: 10px;">
   <strong>Atenção!</strong> Algumas características da mensagem:
   <ul>
      <li>A mensagem abaixo pode ser escrita em HTML.</li>
      <li>A mensagem deve conter alguns atributos que serão substituídos no
         envio do email. São eles:
         <ul>
            <li><code>{nome}</code></li>
            <li><code>{email}</code></li>
            <li><code>{senha}</code></li>
            <li><code>{href_link}</code></li>
         </ul>
      </li>
      <li>Não é necessário escrever cabeçalhos, escreva apenas o conteúdo do <code>&lt;body&gt;</code>.</li>
      <li>Não é possível importar folhas de estilo (css) ou arquivos javascript (js),
         pois os próprios servidores de e-mail irão bloqueá-los. Para utilizar css
         você deve usar o atributo <code>style</code>.
      </li>
   </ul>
</div>
<?php
   $this->headScript()
        ->prependFile($this->baseUrl('js/admin/encontro/salvar.js'), 'text/javascript')
        ->prependFile($this->baseUrl('js/jquery-ui-1.8.16.custom.min.js'), 'text/javascript')
        ->prependFile($this->baseUrl('js/jquery-1.8.3.min.js'));
   
   $this->headLink()
           ->appendStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery.ui.1.8.16.ie.css'))
           ->appendStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery-ui-1.8.16.custom.css'))
           ->appendStylesheet($this->baseUrl('css/screen.css'))
           ->appendStylesheet($this->baseUrl('css/form-evento.css'));
   echo $this->form;

?>
