
<a href="<? echo $this->url(array('module' => 'admin',
   'controller' => 'evento',
   'action' => 'index'), 'default', true) ?>"
   class="no-bottom"><i class="icon-reply"></i> Voltar</a>&nbsp;&nbsp;&nbsp;

<?=$this->url_situacao ?>&nbsp;&nbsp;&nbsp;

<a href="<?=$this->url(array('controller' => 'evento',
   'action' => 'editar',
   'id' => $this->evento['id_evento']), 'default', true) ?>"
   class="no-bottom"><i class="icon-edit"></i> Editar</a>&nbsp;&nbsp;&nbsp;
<?=$this->url_apresentado ?>

<br><br>

<div class="container">
   <div class="span-2">
      Título:
   </div>
   <div class="span-10">
      <?=$this->evento['nome_evento'] ?>
   </div>
</div>

<hr/>

<div class="container">
   <div class="span-6">
      Autor:
      <?=$this->evento['nome'] ?>
   </div>
   <div class="span-4">
      Tipo:
      <?=$this->evento['nome_tipo_evento'] ?>
   </div>
   <div class="span-8">
      Enviar e-mail:&nbsp;
      <a href="mailto:<?=$this->evento['email'] ?>"
         target="_blank" class="no-bottom">
         <i class="icon-envelope"></i> <?=$this->evento['email'] ?>
      </a>
   </div>
</div>

<br/>

<div class="container">
   <div class="span-2">
      Submissão:
   </div>
   <div class="span-6">
      <?=$this->evento['data_submissao'] ?>
   </div>
   <div class="span-1">
      Nível:
   </div>
   <div class="span-4">
      <?=$this->evento['descricao_dificuldade_evento'] ?>
   </div>
   <div class="span-2">
      Validada?:
   </div>
   <div class="span-2">
      <?=($this->evento['validada'] ? "Sim" : "Não") ?>
   </div>
</div>

<br/>

<div class="container">
   <div class="span-20 prepend-2" id="tabs">
      <ul>
			<li><a href="#tab-1">Resumo</a></li>
			<li><a href="#tab-2">Preferência de horário</a></li>
			<li><a href="#tab-3">Tecnologias Envolvidas</a></li>
		</ul>
		<div id="tab-1">
			<?= $this->evento['resumo'] ?>
		</div>
		<div id="tab-2">
			<?= $this->evento['preferencia_horario'] ?>
		</div>
		<div id="tab-3">
			<?= $this->evento['tecnologias_envolvidas'] ?>
		</div>
   </div>
</div>

<br><br>

<fieldset>
   <i class="icon-time"></i> Horários:
   <a href="<?php echo $this->url(array(
      'controller' => 'horario',
      'action' => 'criar',
      'id' => $this->evento['id_evento']));
   ?>" class="no-bottom" style="float: right"><i class="icon-plus"></i>  Novo Horário</a><br>
   <table id="horarios" class="display" cellpadding="0" cellspacing="0" border="0">
      <thead>
         <tr>
            <th>Descrição</th>
            <th style="width: 50px;">Data</th>
            <th style="width: 60px;">Horário</th>
            <th>Sala</th>
            <th style="width: 100px;">Ações</th>
         </tr>
      </thead>
      <tbody>
      <? foreach ($this->horarios as $item): ?>
			<tr>
				<td><? echo $item["descricao"]; ?></td>
				<td><? echo $item["data"]; ?></td>
				<td><? echo $item["inicio"]; ?> - <? echo $item["fim"]; ?></td>
				<td><? echo $item["nome_sala"]; ?></td>
				<td>
					<a href="<?=$this->url(array('module' => 'admin',
						'controller' => 'horario',
						'action' => 'editar',
						'id' => $item['evento'],
						'evento' => $this->evento['id_evento']), 'default', true) ?>"
						class="btn no-bottom" title="Editar"><i class="icon-edit"></i></a>
					<a href="<?=$this->url(array('module' => 'admin',
						'controller' => 'horario',
						'action' => 'deletar',
						'id' => $item['evento'],
						'evento' => $this->evento['id_evento']), 'default', true) ?>"
						class="btn no-bottom" title="Deletar"><i class="icon-remove"></i></a>
				</td>
			</tr>
      <? endforeach; ?>
      </tbody> 
   </table>
   
</fieldset>
<br/>

<fieldset>
   <i class="icon-file"></i> Arquivos (em desenvolvimento):<br>
   <table class="display" cellpadding="0" cellspacing="0" border="0" >
      <thead>
         <tr>
            <th>Arquivos</th>
            <th>Remover Arquivo</th>
         </tr>
      </thead>
      <tbody>
      </tbody> 
   </table>
</fieldset>