<?php echo $this->partial('menu.phtml'); ?>

<input type="radio" class="radio" name="tipo_evento" id="tipo_evento" value="0" checked="checked" /><label>Todos</label><br>
<? foreach ( $this->tipoEvento as $tipoEvento ) {?>
       <input type="radio" class="radio"  name="tipo_evento" id="tipo_evento" value="<?=$tipoEvento->id_tipo_evento?>" /><label><?=$tipoEvento->nome_tipo_evento?></label><br>

<?}
?>
<br>
<input type="radio" class="radio" name="atividades" id="atividades" value="0" checked="checked" /><label>Todos</label><br>
<input type="radio" class="radio" name="atividades" id="atividades" value="1"  /><label>Validadas</label><br>
<input type="radio" class="radio" name="atividades" id="atividades" value="2"  /><label>Não-Validadas</label><br>


<br>Buscar Atividade: <input type="text" class="text" name="nome_evento" id="nome_evento" value="" size="50" maxlength="50" />

<table id="compra" class="display" cellpadding="0" cellspacing="0" border="0"  >
		<thead>
			<tr>
				<th>Tipo Evento</th>
				<th>Evento</th>
				<th>Validada</th>
				<th>Data Submissão</th>
				<th>Responsável</th>
				<th>Detalhes<th>
			</tr>
		</thead>
		<tbody id="resultadoAtividades">
		</tbody>
</table>