<!DOCTYPE html>
<html>
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>SiGE - Oh-ouh!</title>
      <?php
      $this->headLink()->appendStylesheet($this->baseUrl('css/sigecss.css'));
      $this->headLink()->appendStylesheet($this->baseUrl('css/screen.css'));
      $this->headLink()->prependStylesheet($this->baseUrl('css/font-awesome.min.css'));
      $this->headLink()->prependStylesheet($this->baseUrl('css/font-awesome-ie7.min.css'));
      ?>
      <?php echo $this->headLink() ?>
   </head>
   <body>
      <div id="principal">
         <div id="corpo">
            <div id="conteudo">
               <?php echo $this->layout()->content ?>
            </div>

            <div id="rodape">
               <?php echo $this->render('rodape.phtml') ?>
            </div>
         </div>
      </div>
   </body>
</html>
