<?php
$cache = Zend_Registry::get('cache_common');
$ps = $cache->load('prefsis');
$apelido_encontro = $ps->encontro["apelido_encontro"];
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sistema de Gerência de Eventos">
    <meta name="author" content="COMSOLiD -  Comunidade Maracanauense de Software Livre e Inclusão Digital">
    <link rel="icon" href="<?php echo $this->baseUrl('imagens/layout/favicon_sige.png'); ?>">

    <title><?php echo $apelido_encontro; ?> - SiGE</title>
    <?php
    $this->headLink()->appendStylesheet($this->baseUrl('css/sigecss.css'));
    $this->headLink()->prependStylesheet($this->baseUrl('lib/css/font-awesome/font-awesome.min.css'));
    $this->headLink()->prependStylesheet($this->baseUrl('lib/css/bootstrap/navbar-fixed-top.css'));
    $this->headLink()->prependStylesheet($this->baseUrl('lib/css/bootstrap/default/bootstrap.min.css'));
    ?>

    <?php
    //$this->headScript()->prependFile($this->baseUrl('js/utils.js'));
    //$this->headScript()->prependFile($this->baseUrl('js/jed/jed-init.js'));
    //$this->headScript()->prependFile($this->baseUrl('js/jed/locale/pt_BR.js'));
    //$this->headScript()->prependFile($this->baseUrl('js/jed/jed.js'));
    $this->headScript()->prependFile($this->baseUrl('lib/js/bootstrap/bootstrap.min.js'));
    $this->headScript()->prependFile($this->baseUrl('js/jquery-1.10.2.min.js'));
    ?>

    <?= $this->headLink() ?>
    <?= $this->headStyle() ?>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,500">
    <style>
    body {
        font-family: 'Source Sans Pro', "Helvetica Neue", Helvetica, Arial;
        font-size: 15px;
    }
    </style>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- HINT: REMOVE ME IN PRODUCTION! -->
    <!--<script src="http://localhost:35729/livereload.js"></script>-->
</head>

<body>

    <?php echo $this->layout()->content; ?>

    <?= $this->headScript() ?>
</body>
</html>
