
<div id="menu" class="fl_left">
	<a href="<?php echo $this->url(array('controller'=>'participante','action'=>'index'));?>"><img src="/imagens/layout/btmenu_inicio.png"></img></a>
	<a href="<?php echo $this->url(array('controller'=>'participante','action'=>'alterarsenha'));?>"><img src="/imagens/layout/btmenu_mudarsenha.png"></img></a>
	<a href="#"><img src="/imagens/layout/btmenu_caravana.png"></img></a> 
	<a href="<?php echo $this->url(array('controller'=>'evento','action'=>'meuseventos'));?>"><img src="/imagens/layout/btmenu_meuseventos.png"></img></a>
  
	<a href="#" class="verde fl_right"><img src="/imagens/layout/bt_sejavoluntario.png"></img></a>
</div>


<div id="menu" class="fl_left inativo">
	<a href="#" class="verde fl_left"><img src="/imagens/layout/bt_inscricao.png"></img></a>
	<img src="/imagens/layout/btmenu_inicio.png"></img>
	<img src="/imagens/layout/btmenu_mudarsenha.png"></img>
	<img src="/imagens/layout/btmenu_caravana.png"></img>
	<img src="/imagens/layout/btmenu_meuseventos.png"></img>
</div>