<?php echo $this->partial('menu.phtml'); ?>

<div class="container">
   <div class="span-8 prepend-1">
      <h3>Usuários</h3><hr/>
      <a href="<?php echo $this->url(array(
         'module' => 'admin',
         'controller' => 'config',
         'action' => 'permissao-usuarios'), 'default', true); ?>"
         class="no-bottom"><i class="icon-lock"></i> Permissão de usuários</a>
   </div>
</div>
