<?php
$this->headScript()
        ->prependFile($this->baseUrl('js/ckeditor.js'), 'text/javascript');
?>

<br>
<br>

<?php echo $this->form; ?>

<?php if (count($this->realizacao) > 0): ?>
   <table id="compra" class="display" cellpadding="0" cellspacing="0" border="0">
      <thead>
         <th>Data</th>
         <th>Hora Início</th>
         <th>Hora Fim</th>
         <th>Sala</th>
   </thead>
   <tbody> 
      <?php foreach ($this->realizacao as $linha): ?>
         <tr>
            <td><?=$linha["data"] ?></td>
            <td><?=$linha["hora_inicio"] ?></td>
            <td><?=$linha["hora_fim"] ?></td>
            <td><?=$linha["nome_sala"] ?></td>
         </tr>
      <?php endforeach; ?>
   </tbody>
</table>

<?php endif; ?>
