<?php
    $this->headLink()->appendStylesheet($this->baseUrl('css/tabela_sort.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/tipsy.css'));

    $this->headScript()->appendFile($this->baseUrl('js/jquery.dataTables.js'));
    $this->headScript()->appendFile($this->baseUrl('js/jquery.tipsy.js'));
    $this->headScript()->appendFile($this->baseUrl('js/evento/inicio.js'));
?>

<a href="<?php echo $this->url(array('controller'=>'evento',
    'action'=>'submeter'), 'default');?>" class="no-bottom">
   <i class="icon-file"></i> <?php echo $this->translate("Submit Paper"); ?></a>
<br/><br/>

<?php if(count($this->meusEventos)>0): ?>

   <table class="display" cellpadding="0" cellspacing="0" border="0" >
      <thead>
         <tr>
            <th><?php echo $this->translate("Event Type"); ?></th>
            <th><?php echo $this->translate("Event"); ?></th>
            <th><?php echo $this->translate("Validated"); ?></th>
            <th><?php echo $this->translate("Submission Date"); ?></th>
            <th style="width: 100px;">&nbsp;</th>
         </tr>
      </thead>
      <tbody>
         <?php foreach ($this->meusEventos as $linha): ?>
            <tr>
               <td><?= $linha["nome_tipo_evento"] ?></td>
               <td><?= $linha["nome_evento"] ?></td>
               <td>
                  <?php if ($linha["validada"]): ?>
                     <i class="icon-thumbs-up-alt"></i> <?php echo $this->translate("Yes"); ?>
                  <?php else: ?>
                     <i class="icon-thumbs-down-alt"></i> <?php echo $this->translate("No"); ?>
                  <?php endif; ?>
               </td>
               <td><?= $linha["data_submissao"] ?></td>
               <td>
                  <a href="<?php echo $this->url(array('controller'=>'evento',
                     'action'=>'editar',
                      'id'=>$linha['id_evento']), 'default', true);?>" class="no-bottom">
                     <i class="icon-edit"></i> <?php echo $this->translate("Edit"); ?></a>&nbsp;&nbsp;&nbsp;
                  <a href="<?php echo $this->url(array('controller'=>'evento',
                     'action'=>'outros-palestrantes',
                     'id'=>$linha['id_evento']), 'default', true);?>" class="no-bottom tooltip"
                     title="<?php echo $this->translate("Add other speakers"); ?>">
                     <i class="icon-group"></i></a>&nbsp;&nbsp;&nbsp;
                  <a href="<?php echo $this->url(array('controller'=>'evento',
                     'action' => 'tags',
                     'id' => $linha['id_evento']), 'default', true);?>" class="no-bottom tooltip"
                     title="<?php echo $this->translate("Create/Edit tags"); ?>">
                     <i class="icon-tags"></i></a>
               </td>
            </tr>
         <?php endforeach; ?>
      </tbody>
   </table>
<br>

<?php else: ?>
   <br><?php echo $this->translate("What about submit a paper and participate?"); ?>
<?php endif; ?>
