<?php
    $this->headLink()->appendStylesheet($this->baseUrl('css/tabela_sort.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/tipsy.css'));

    $this->headScript()->appendFile($this->baseUrl('js/jquery.dataTables.js'));
    $this->headScript()->appendFile($this->baseUrl('js/jquery.tipsy.js'));
    $this->headScript()->appendFile($this->baseUrl('js/evento/inicio.js'));
?>

<?php if(count($this->meusEventos) > 0): ?>

<div class="row">
    <div class="col-md-6">
        <h3>Trabalhos Submetidos</h3>
    </div>
    <div class="col-md-6">
        <a href="<?php echo $this->url(array('controller'=>'evento',
            'action'=>'submeter'), 'default');?>" class="btn btn-primary btn-lg pull-right">
           <i class="fa fa-file"></i> <?php echo $this->translate("Submit Paper"); ?>
        </a>
    </div>
</div>

<hr>

    <?php foreach ($this->meusEventos as $linha): ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <span class="label label-primary"><?= $linha["nome_tipo_evento"] ?></span>
                <?= $linha["nome_evento"] ?>
            </h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <?= $linha["resumo"] ?>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-4">
                    Submetido em <?= $linha["data_submissao"] ?>
                </div>
                <div class="col-md-4">
                    <?php if ($linha["validada"]): ?>
                       <span class="label label-success">
                           <i class="fa fa-check"></i>
                           <?php echo $this->translate("Validated"); ?>
                       </span>
                    <?php else: ?>
                       <span class="label label-warning">
                           <i class="fa fa-times"></i>
                           <?php echo $this->translate("Not validated yet"); ?>
                       </span>
                    <?php endif; ?>
                </div>
                <div class="col-md-4">
                    <div class="btn-group pull-right">
                        <a href="<?php echo $this->url(array('controller'=>'evento',
                           'action'=>'editar',
                            'id'=>$linha['id_evento']), 'default', true);?>" class="btn btn-default">
                           <i class="fa fa-edit"></i> <?php echo $this->translate("Edit"); ?>
                        </a>
                        <a href="<?php echo $this->url(array('controller'=>'evento',
                           'action'=>'outros-palestrantes',
                           'id'=>$linha['id_evento']), 'default', true);?>" class="btn btn-default"
                           title="<?php echo $this->translate("Add other speakers"); ?>">
                           <i class="fa fa-group"></i>
                        </a>
                        <a href="<?php echo $this->url(array('controller'=>'evento',
                           'action' => 'tags',
                           'id' => $linha['id_evento']), 'default', true);?>" class="btn btn-default"
                           title="<?php echo $this->translate("Create/Edit tags"); ?>">
                           <i class="fa fa-tags"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php endforeach; ?>

<?php else: ?>
   <div class="row">
       <div class="col-md-12">
           <h3 class="text-center">
               <?php echo $this->translate("What about submit a paper and participate?"); ?>
           </h3>
       </div>
   </div>

   <div class="row">
       <div class="col-md-4"><hr></div>
       <div class="col-md-4">
           <a href="<?php echo $this->url(array(
               'controller'=>'evento',
               'action'=>'submeter'), 'default');?>"
               class="btn btn-primary btn-lg btn-block">
              <i class="fa fa-file"></i> <?php echo $this->translate("Submit Paper"); ?>
           </a>
       </div>
       <div class="col-md-4"><hr></div>
   </div>
<?php endif; ?>
