<?php
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/data-tables/dataTables.bootstrap.css'));

    $this->headScript()->appendFile($this->baseUrl('js/jquery-ui-1.8.16.custom.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/data-tables/jquery.dataTables.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/data-tables/dataTables.bootstrap.js'));
    $this->headScript()->appendFile($this->baseUrl('js/evento/interesse.js'));
?>

<h3><?php echo $this->translate("Add events of your interest"); ?></h3><hr>

<div class="row">
    <div class="col-md-6">
        <p>
            <i class="fa fa-calendar"></i>
            <b>Dias:</b>
        </p>
        <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-default active">
                <input type="radio" name="data_evento" class="data_evento"
                       id="radio_data_todos" value="todas" checked="checked" />
                <?php echo $this->translate("All"); ?>
            </label>
            <?php foreach ($this->diasEncontro as $value): ?>
            <label class="btn btn-default">
                <input type="radio" name="data_evento" class="data_evento"
                       id="radio_<?= $value['data'] ?>"
                       value="<?= str_replace('/', '-', $value['data']) ?>" />
                <?php echo $value['data']; ?>
            </label>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-md-6">
        <p>
            <i class="fa fa-star"></i>
            <b>Tipo de evento:</b>
        </p>
        <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-default active">
                <input type="radio" name="tipo_evento" class="tipo_evento"
                       id="radio_tipo_todos" value="0" checked="checked" />
                <?php echo $this->translate("All"); ?>
            </label>
            <?php foreach ($this->tipoEvento as $tipoEvento): ?>
            <label class="btn btn-default">
                <input type="radio" name="tipo_evento" class="tipo_evento"
                       id="radio_<?= $tipoEvento->id_tipo_evento ?>"
                       value="<?= $tipoEvento->id_tipo_evento ?>" />
                <?php echo $tipoEvento->nome_tipo_evento; ?>
            </label>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <input type="text" id="termo" class="form-control input-lg"
                placeholder="<?php echo $this->translate("Search event..."); ?>"/>
        </div>
    </div>
    <div class="col-md-2">
        <i class="fa fa-spinner fa-2x fa-spin" id="loading"></i>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="alert alert-success" id="msg-success" style="display: none;"></div>
        <div class="alert alert-danger" id="msg-error" style="display: none;"></div>
    </div>
</div>

<table id="example" cellpadding="0" cellspacing="0" class="table table-striped">
    <thead>
        <tr>
            <th><?php echo $this->translate("Description"); ?></th>
            <th><?php echo $this->translate("Date"); ?></th>
            <th><?php echo $this->translate("Time"); ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody id="resultado">
    </tbody>
</table>

<hr>

<div class="alert alert-warning">
   <p>
       <strong><?php echo $this->translate("Attention!"); ?></strong>
       <?php echo $this->translate("Bookmark an event do not guarantee your spot. So arrive early."); ?><br/>
       <?php echo $this->translate("Bookmark events it's only a way to organize the places depending on demand."); ?>
   </p>
</div>
