<div class="container">
   <div class="span-14" id="radioset_data">
      <i class="icon-calendar"></i>
      <input type="radio" name="data_evento" class="data_evento"
             id="radio_data_todos" value="todas" checked="checked" />
      <label for="radio_data_todos"><?php echo $this->translate("All"); ?></label>
      <?php foreach ($this->diasEncontro as $value): ?>
      <input type="radio" name="data_evento" class="data_evento" id="radio_<?= $value['data'] ?>"
                value="<?= str_replace('/', '-', $value['data']) ?>" />
      <label for="radio_<?= $value['data'] ?>"><?= $value['data'] ?></label>
      <?php endforeach; ?>
   </div>
</div><br/>
<div class="container">
   <div class="span-14" id="radioset_tipo">
      <i class="icon-star"></i>
      <input type="radio" name="tipo_evento" class="tipo_evento" id="radio_tipo_todos"
             value="0" checked="checked" /><label for="radio_tipo_todos"><?php echo $this->translate("All"); ?></label>
      <?php foreach ($this->tipoEvento as $tipoEvento): ?>
      <input type="radio" name="tipo_evento" class="tipo_evento"
                id="radio_<?= $tipoEvento->id_tipo_evento ?>"
                value="<?= $tipoEvento->id_tipo_evento ?>" />
      <label for="radio_<?= $tipoEvento->id_tipo_evento ?>"><?= $tipoEvento->nome_tipo_evento ?></label>
      <?php endforeach; ?>
   </div>
</div>
<br>
<input type="text" class="text" name="termo" id="termo"
       value="" size="50" maxlength="50" placeholder="<?php echo $this->translate("Search event..."); ?>" style="float: left;" />
<img id="loading" src="<?=$this->baseUrl('img/loading.gif') ?>"
     style="display: none; float: left;" />
<br><br>
<div class="success" style="display: none;"></div>
<div class="error" style="display: none;"></div>

<fieldset>
   <table class="display" cellpadding="0" cellspacing="0" border="0"  >
      <thead>
         <tr>
            <th><?php echo $this->translate("Event"); ?></th>
            <th><?php echo $this->translate("Description"); ?></th>
            <th><?php echo $this->translate("Date"); ?></th>
            <th><?php echo $this->translate("Time"); ?></th>
            <th>&nbsp;</th>
         </tr>
      </thead>
      <tbody id="resultado">
      </tbody>
   </table>
</fieldset>

<div class="notice">
   <p><strong><?php echo $this->translate("Attention!"); ?></strong>
      <?php echo $this->translate("Bookmark an event do not guarantee your spot. So arrive early."); ?><br/>
      <?php echo $this->translate("Bookmark events it's only a way to organize the places depending on demand."); ?>
   </p>
</div>