<?php
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/select2/select2.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/select2/select2-bootstrap.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/alertifyjs/alertify.min.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/alertifyjs/themes/bootstrap.min.css'));

    $this->headScript()->appendFile($this->baseUrl('lib/js/select2/select2.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/select2/select2_locale_pt-BR.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/data-tables/jquery.dataTables.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/data-tables/dataTables.bootstrap.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/alertifyjs/alertify.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/alertifyjs/alertify.override.js'));
    $this->headScript()->appendFile($this->baseUrl('js/evento/outros-palestrantes.js'));

?>

<h4>
    <?php echo $this->translate("Add other speakers:"); ?>
    <strong><?php echo $this->evento['nome_evento'] ?></strong>
</h4>

<hr>

<form action="<?php echo $this->url(array('action' => 'outros-palestrantes')) ?>" method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <input type="hidden" id="sel" name="array_id_pessoas" class="form-control"/>
            </div>
        </div>
        <div class="col-md-3">
            <input type="submit" name="submit" id="submit"
            class="btn btn-primary"
            value="<?php echo $this->translate("Confirm"); ?>"/>
        </div>
    </div>
</form>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <table class="table table-striped">
            <thead>
                <th><?php echo $this->translate("Speakers"); ?></th>
                <th>&nbsp;</th>
            </thead>
            <tbody>
            <?php foreach ($this->palestrantes as $palestrante): ?>
                <tr>
                    <td><?php echo $palestrante['nome'] ?></td>
                    <td>
                        <div class="btn-group pull-right">
                            <a title="<?php echo $this->translate("Remove the speaker from this event"); ?>"
                              href="<?php echo $this->url(array('controller' => 'evento',
                                     'action' => 'deletar-palestrante',
                                     'pessoa' => $palestrante['id_pessoa'],
                                     'evento' => $this->evento['id_evento']), 'default', true);
                                ?>" class="btn btn-danger deletar"
                                data-toggle="tooltip" data-placement="top">
                              <i class="fa fa-times"></i> <?php echo $this->translate("Delete"); ?>
                            </a>
                            <a href="mailto:<?php echo $palestrante['email'] ?>" target="_blank"
                                class="btn btn-default"
                                title="<?php echo $this->translate("Send e-mail"); ?>"
                                data-toggle="tooltip" data-placement="top">
                                <i class="fa fa-envelope-o"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
