<?php
    $this->headLink()->appendStylesheet($this->baseUrl('css/prettify.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/jquery-ui-bootstrap/jquery-ui-1.9.2.custom.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/evento/programacao.css'));

    $this->headScript()->appendFile($this->baseUrl('lib/js/jquery-ui-bootstrap/jquery-ui-1.9.2.custom.min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/prettify.js'));
    $this->headScript()->appendFile($this->baseUrl('js/init.prettify.js'));
    $this->headScript()->appendFile($this->baseUrl('js/moment-with-langs.min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/evento/programacao.js'));
?>

<div class="row">
    <div class="col-md-6">
        <h3><?php echo $this->translate("Schedule"); ?></h3>
    </div>
    <div class="col-md-2">
        <div class="checkbox">
            <label>
                <input type="checkbox" id="auto-scroll"/>
                <?php echo $this->translate("Auto scroll?"); ?>
            </label>
        </div>
    </div>
    <div class="col-md-4">
        <div class="btn-group pull-right" data-toggle="buttons">
            <label class="btn btn-default active">
                <input type="radio" name="mode" id="normal-mode" autocomplete="off" checked>
                <?php echo $this->translate("Normal"); ?>
            </label>
            <label class="btn btn-default">
                <input type="radio" name="mode" id="print-mode" autocomplete="off">
                <?php echo $this->translate("Print"); ?>
            </label>
        </div>
    </div>
</div>

<hr/>

<?php
$data_atual = null;
if (! empty($this->lista)):
   foreach ($this->lista as $item): ?>
<div class="row">
   <div class="col-md-1 col-md-offset-1">
      <?php
      if ($item['data'] != $data_atual) {
         $date = new Zend_Date($item['data'], 'dd/MM/y');
      ?>
      <div class="prog-date">
         <p><?php echo $date->toString('dd') ?> <span><?php echo $date->toString('MMM') ?></span></p>
      </div>
      <?php
         $data_atual = $item['data'];
      } else {
         echo "&nbsp;";
      }
      ?>
   </div>
   <div class="col-md-7 <?php echo $item['dia_mes'] ?>"
        data-data="<?php echo $item['data'] ?>"
        data-hora="<?php echo $item['hora_inicio'] ?>">
      <div class="acc-evento">
         <div class="header3">
            <?php echo $item['nome_tipo_evento'] ?>: <?php echo $item['nome_evento'] ?>
            <?php if (! empty($item['descricao'])) : ?>
            (<?php echo $item['descricao'] ?>)
            <?php endif; ?>
         </div>
         <div>
            <div>
                <?php echo $this->translate("Place"); ?>:
                <?php echo $item['nome_sala'] ?>
                -
                <?php echo $this->translate("from"); ?>
                <?php echo $item['hora_inicio'] ?>
                <?php echo $this->translate("to"); ?>
                <?php echo $item['hora_fim'] ?></div>
                <hr/>
                <?php
                if (! empty($item['twitter'])) {
                   $id = $item['twitter'];
                } else {
                   $id = $item['id_pessoa'];
                }
                ?>
            <div>
               <?php echo $this->translate("by"); ?>
               <a href="<?php echo $this->url(array('id' => $id),
                    'ver', true) ?>" target="blank"><?php echo $item['nome'] ?></a>
               <?php if ($item['outros'] == 1): ?>
                  <?php echo $this->translate("and other."); ?>
               <?php elseif ($item['outros'] > 1): ?>
                  <?php echo sprintf($this->translate("and %d others."), $item['outros']); ?>
               <?php endif; ?>
            </div>
            <p><?php echo $item['resumo'] ?></p>
         </div>
      </div>
   </div>
   <div class="col-md-1">
      <a href="<?php echo $this->url(array('id' => $item['id_evento']), 'ver_evento', true) ?>#disqus_thread"
              class="btn btn-default" rel="tooltip"
              title="<?php echo $this->translate("View and post comments"); ?>">
              <i class="fa fa-comments-o"></i>
      </a>
   </div>
</div>
<?php
   endforeach;
else:
?>
<div class="notice" style="margin-top: 10px;">
   <div class="msg-header"><?php echo $this->translate("Attention!"); ?></div>
   <div><?php echo $this->translate("There are no events on our schedule yet. Be the first to"); ?>
      <a href="<?php echo $this->url(array('controller'=>'evento',
    'action'=>'submeter'), 'default');?>"
    class="no-bottom"><i class="icon-file"></i> <?php echo $this->translate("Submit a paper"); ?></a></div>
</div>
<?php endif; ?>
