
<div class="container">
   <div class="span-15">
      <h3><?php echo $this->translate("Schedule"); ?></h3>
   </div>
   <div class="span-6">
      <div style="float: right">
         <?php echo $this->translate("Mode:"); ?>
         <a href="#" id="modo-normal" onclick="return false;" class="no-bottom">
             <?php echo $this->translate("Normal"); ?>
         </a> |
         <a href="#" id="modo-impressao" onclick="return false;" class="no-bottom">
             <?php echo $this->translate("Print"); ?>
         </a>
      </div>
   </div>
</div>

<hr/>
<?php
$data_atual = null;
if (! empty($this->lista)):
   foreach ($this->lista as $item): ?>
<div class="container">
   <div class="span-2">
      <?php
      if ($item['data'] != $data_atual) {
         $date = new Zend_Date($item['data'], 'dd/MM/y');
      ?>
      <div class="prog-date">
         <p><?=$date->toString('dd') ?> <span><?=$date->toString('MMM') ?></span></p>
      </div>
      <?php
         $data_atual = $item['data'];
      } else {
         echo "&nbsp;";
      }
      ?>
   </div>
   <div class="span-18">
      <div class="acc-evento">
         <div class="header3">
            <?=$item['nome_tipo_evento'] ?>: <?=$item['nome_evento'] ?>
            <?php if (! empty($item['descricao'])) : ?>
            (<?=$item['descricao'] ?>)
            <?php endif; ?>
         </div>
         <div>
            <div>
                <?php echo $this->translate("Place"); ?>
                <?=$item['nome_sala'] ?>
                <?php echo $this->translate("from"); ?>
                <?=$item['hora_inicio'] ?>
                <?php echo $this->translate("to"); ?>
                <?=$item['hora_fim'] ?></div>
                <hr/>
                <?php
                if (! empty($item['twitter'])) {
                   $id = $item['twitter'];
                } else {
                   $id = $item['id_pessoa'];
                }
                ?>
            <div>
               <?php echo $this->translate("by"); ?>
               <a href="<?=$this->url(array('id' => $id),
                    'ver', true) ?>" target="blank"><?=$item['nome'] ?></a>
               <?php if ($item['outros'] == 1): ?>
                  <?php echo $this->translate("and other."); ?>
               <?php elseif ($item['outros'] > 1): ?>
                  <?php echo sprintf($this->translate("and %d others."), $item['outros']); ?>
               <?php endif; ?>
            </div>
            <p><?=$item['resumo'] ?></p>
         </div>
      </div>
   </div>
   <div class="span-1">
      <a href="<?=$this->url(array('id' => $item['id_evento']),
              'ver_evento', true) ?>#disqus_thread" class="no-bottom"
              title="<?php echo $this->translate("View and post comments"); ?>">
              <i class="icon-comments-alt"></i>
      </a>
   </div>
</div>
<?php
   endforeach;
else:
?>
<div class="notice" style="margin-top: 10px;">
   <div class="msg-header"><?php echo $this->translate("Attention!"); ?></div>
   <div><?php echo $this->translate("There are no events on our schedule yet. Be the first to"); ?>
      <a href="<?php echo $this->url(array('controller'=>'evento',
    'action'=>'submeter'), 'default');?>"
    class="no-bottom"><i class="icon-file"></i> <?php echo $this->translate("Submit a paper"); ?></a></div>
</div>
<?php endif; ?>
