<?php
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/alertifyjs/alertify.min.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/alertifyjs/themes/bootstrap.min.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/jquery-ui-bootstrap/jquery-ui-1.9.2.custom.css'));

    $this->headScript()->appendFile($this->baseUrl('lib/js/alertifyjs/alertify.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/alertifyjs/alertify.override.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/jquery-ui-bootstrap/jquery-ui-1.9.2.custom.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/sprintfjs/sprintf.min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/evento/tags.js'));
?>

<h3>
    <?php echo $this->evento['nome_tipo_evento'] ?>:
    <?php echo $this->evento['nome_evento'] ?>
</h3>

<hr>

<div class="row">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-10">
                <div class="form-group">
                    <input type="text" class="form-control input-lg" id="termo"
                        placeholder="<?php echo $this->translate("Search tag"); ?> ex. python, ruby, java..." />

                    <input type="hidden" id="id_evento" value="<?php echo $this->evento['id_evento'] ?>"/>
                </div>
            </div>
            <div class="col-md-2">
                <i class="fa fa-spinner fa-2x fa-spin" id="loading"></i>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <a id="criar-tag" href="#" class="btn btn-primary"
                    style="display: none;" onclick="return false;">
                    <i class="fa fa-tag"></i> <?php echo $this->translate("Create Tag"); ?>
                </a>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-tags"></i> Tags</h3>
            </div>
            <ul class="list-group">
                <?php foreach ($this->tags as $tag): ?>
                <li class="list-group-item" id="tag_<?php echo $tag['id'] ?>">
                    <?php echo $tag['descricao'] ?>
                    <a href="#" onclick="return false;"
                        class="close remover pull-right"
                        data-id="<?php echo $tag['id'] ?>"
                        data-toggle="tooltip" data-placement="top"
                        title="<?php echo $this->translate("Remove"); ?>">
                       <span aria-hidden="true">&times;</span>
                       <span class="sr-only">Close</span>
                    </a>
                </li>
                <?php endforeach; ?>
            </ul>
            <?php if (count($this->tags) == 0): ?>
            <div class="panel-body">
                <?php echo $this->translate("No tags found."); ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
