
<?php
   $this->headLink()->appendStylesheet($this->baseUrl('css/prettify.css'));

   $this->headScript()->appendFile($this->baseUrl('lib/js/momentjs/moment-with-langs.min.js'));
   $this->headScript()->appendFile($this->baseUrl('js/prettify.js'));
   $this->headScript()->appendFile($this->baseUrl('js/init.prettify.js'));
   $this->headScript()->appendFile($this->baseUrl('js/evento/ver.js'));
?>

<?php if (!empty($this->evento)): ?>

<?php
$config = new Zend_Config_Ini(APPLICATION_PATH . '/configs/application.ini', 'staging');
/* meta tags para twitter */
$this->headMeta()->setName('twitter:card', 'summary');
$this->headMeta()->setName('twitter:description', "{$this->evento['resumo']}");
$this->headMeta()->setName('twitter:site', "@{$config->twitter->username}");
$this->headMeta()->setName('twitter:title', "{$this->evento['nome_evento']}");
$this->headMeta()->setName('twitter:url', "{$this->serverUrl()}{$this->url(array('id' => $this->evento['id_evento']),
              'ver_evento', true)}");
?>

   <div id="fb-root"></div>
   <script>(function(d, s, id) {
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) return;
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=336256479809348";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));</script>

    <div class="row">
        <div class="col-md-9">
            <h3><?php echo $this->evento['nome_tipo_evento'] ?>:
                <strong><?php echo $this->evento['nome_evento'] ?></strong>
            </h3>
        </div>
        <div class="col-md-1">
            <!-- twitter button -->
            <a href="https://twitter.com/share" class="twitter-share-button"
            data-url="<?=$this->serverUrl() . $this->url(array('id' => $this->evento['id_evento']),
              'ver_evento', true) ?>"
              data-text="<?php echo $this->evento['nome_evento'] ?> por <?php echo $this->evento['nome'] ?>"
              data-via="<?=$config->twitter->username ?>"
              data-lang="pt" data-hashtags="<?=$config->twitter->hashtags ?>">Tweetar</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
        <div class="col-md-1">
            <!-- facebook button -->
            <div class="fb-like" data-href="<?=$this->serverUrl() . $this->url(array('id' => $this->evento['id_evento']),
                  'ver_evento', true) ?>" data-send="false" data-layout="button_count"
                  data-width="450" data-show-faces="false"></div>
            </div>
        <div class="col-md-1">
            <!-- Place this tag in your head or just before your close body tag. -->
            <script type="text/javascript" src="https://apis.google.com/js/plusone.js">
               {lang: 'pt-BR'}
            </script>

            <!-- Place this tag where you want the +1 button to render. -->
            <div class="g-plusone" data-size="medium" data-href="<?=$this->serverUrl() . $this->url(array('id' => $this->evento['id_evento']),
                  'ver_evento', true) ?>"></div>
        </div>
    </div>

    <hr/>

    <div class="row">
        <div class="col-md-5">
            <?php echo $this->translate("Speaker:"); ?>
            <?php echo $this->evento['nome'] ?>
        </div>
        <div class="col-md-3">
            <?php echo $this->translate("Submited"); ?>
            <span data-moment="<?php echo $this->evento["data_submissao_f"] ?>" title="<?php echo $this->evento["data_submissao_f"] ?>"></span>
        </div>
        <div class="col-md-3">
            <?php echo $this->translate("Level:"); ?>
            <?php echo $this->evento['descricao_dificuldade_evento'] ?>
        </div>
    </div>

    <br/>

    <div class="row">
        <div class="col-md-10 col-md-offset-1" role="tabpanel">

            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active">
                    <a href="#tab-1" aria-controls="home" role="tab" data-toggle="tab">
                        <?php echo $this->translate("Abstract"); ?>
                    </a>
                </li>
                <li role="presentation">
                    <a href="#tab-2" aria-controls="home" role="tab" data-toggle="tab">
                        <?php echo $this->translate("Other Speakers"); ?>
                    </a>
                </li>
                <li role="presentation">
                    <a href="#tab-3" aria-controls="home" role="tab" data-toggle="tab">
                        <?php echo $this->translate("Profile"); ?>
                    </a>
                </li>
                <li role="presentation">
                    <a href="#tab-4" aria-controls="home" role="tab" data-toggle="tab">
                        <?php echo $this->translate("Bio"); ?>
                    </a>
                </li>
                <li role="presentation">
                    <a href="#tab-5" aria-controls="home" role="tab" data-toggle="tab">
                        <?php echo $this->translate("Tags"); ?>
                    </a>
                </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="tab-1">
                    <p style="margin-top: 10px;"><?php echo $this->evento['resumo'] ?></p>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-2">

                    <?php if (! empty($this->outros)): ?>
                    <div class="list-group" style="margin-top: 10px; width: 400px;">
                    <?php foreach ($this->outros as $outro): ?>
                    <?php
                        $url = "/u/";
                        $url .= (empty($outro['twitter']) ? $outro['id_pessoa'] : $outro['twitter']);
                    ?>
                        <a class="list-group-item" href="<?=$url ?>" target="_blank"><?=$outro['nome'] ?></a>
                    <?php endforeach; ?>
                    </div>
                    <?php else: ?>
                    <p style="margin-top: 10px;"><?php echo $this->translate("Single speaker."); ?></p>
                    <?php endif; ?>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-3">
                    <p style="margin-top: 10px;"><?php echo $this->evento['perfil_minimo'] ?></p>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-4">
                    <p style="margin-top: 10px;">
                        <?php if (! empty($this->evento['bio'])): ?>
                            <?php echo $this->evento['bio']; ?>
                        <?php else: ?>
                            <span class="text-muted"><?php echo $this->translate("Not defined."); ?></span>
                        <?php endif; ?>
                    </p>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-5">
                    <?php if (! empty($this->tags)): ?>
                        <div class="panel panel-default" style="margin-top: 10px; width: 400px;">
                            <ul class="list-group">
                            <?php if (! empty($this->tags)):
                                foreach ($this->tags as $tag): ?>
                                <li class="list-group-item">
                                    <?=$tag['descricao'] ?>
                                </li>
                            <?php    endforeach;
                            endif; ?>
                            </ul>
                        </div>
                    <?php else: ?>
                        <p style="margin-top: 10px;" class="text-muted">
                            <?php echo $this->translate("No tags defined."); ?>
                        </p>
                    <?php endif; ?>
                </div>

            </div><!-- end of Tab panes -->
        </div><!-- end of role=tabpanel -->
    </div><!-- end of .row -->

    <hr/>

    <div class="row">
        <div class="col-md-12">
            <div id="disqus_thread" class="text-center">
                <a href="#" id="btn-load-disqus" class="btn btn-default btn-lg">
                    <i class="fa fa-comments"></i>
                    Mostrar Comentários
                </a>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'comsolid';
        var disqus_title = '<?php echo $this->evento['nome_evento'] ?>';
        var disqus_url = '<?php echo $this->serverUrl() . $this->url(array('id' => $this->evento['id_evento']), 'ver_evento', true) ?>';
    </script>
    <noscript>Por favor, habilite o JavaScript para ver os <a href="http://disqus.com/?ref_noscript">comentários do Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink pull-right">comments powered by <span class="logo-disqus">Disqus</span></a>

<?php endif; ?>
