
<? /*<a href="<?=$this->url(array('action' => 'certificado-palestrante'),
        'default') ?>">Certificado Palestrante</a><br/><br/> //teste */?>

<fieldset>
   <a title="Adicionar interesse em Evento" style="float:right; clear:right;"
			href="<?=$this->url(array('controller' => 'evento',
             'action' => 'interesse')) ?>" class="no-bottom">
		<i class="icon-plus"></i> Ver e adicionar eventos do seu interesse
	</a>
	<table class="display" cellpadding="0" cellspacing="0" border="0">
		<thead>
			<tr>
				<th>Tipo evento</th>
				<th>Descrição</th>
				<th>Dia</th>
				<th>Hora Início</th>
				<th>Hora Fim</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
		<? foreach ( $this->listaParticipanteEventoTabela as $item ): ?>
			<tr>
				<td><?echo $item["nome_tipo_evento"];?></td>
				<td>
               <? if (!$item['validada']): ?>
                  <i class="icon-warning-sign" title="Este evento foi invalidado e pode não ser ministrado."></i>
               <? endif; ?>
               <? echo $item["nome_evento"];?>
            </td>
				<td><? echo $item["data"];?></td>
				<td><? echo $item["hora_inicio"];?></td>
				<td><? echo $item["hora_fim"];?></td>
				<td>
					<a href="<?=$this->url(array(
                   'controller' => 'evento',
                   'action' => 'desfazer-interesse',
                   'id' => $item["evento"])) ?>" class="no-bottom">
                  <i class="icon-reply"></i> Desfazer</a>
					<!--<a href="<?// echo $this->baseUrl('/participante/excluievento/evento/'.$item["evento"]);?>">Excluir</a>-->
				</td>
		  </tr>
		<? endforeach; ?>
		</tbody>
	</table>
</fieldset>
