<?php

?>
<? if (! empty($this->user)): ?>
<p>
   <a href="<?=$this->url(array('id' => $this->id),
        'ver') ?>">Página de <?=$this->user->nome ?></a>
   <? if ($this->mostrarEditar) : ?>
   | <a href="<?php echo $this->url(array('controller'=>'participante',
         'action'=>'editar'), 'default');?>">
      Editar
   </a>
   <? endif; ?>
</p>
<p>Meu nome é <?=$this->user->nome ?>.</p>
<p>
   Sobre mim: <?=$this->user->bio ?>
</p>
<?
if (! empty($this->user->twitter)) {
   $twitter = "Me siga no <a href='https://twitter.com/#!/{$this->user->twitter}'
>Twitter</a>.";
} else {
   $twitter = "Ainda não possuo <a href='https://twitter.com'>Twitter</a>.";
}
?>
<p><?=$twitter ?></p>

<? else: ?>
<p>Participante não encontrado.</p>
<? endif; ?>