<style>
   .inicio {
      background-color: #0099CC;
      color: white;
      padding: 10px;
   }

   .programacao {
      background-color: #CC0000;
      color: white;
      padding: 10px;
   }

   .login {
      background-color: #FF8800;
      color: white;
      padding: 10px;
   }

   .participar {
      background-color: #669900;
      color: white;
      padding: 10px;
   }

   .span-4 h3, .span-4 a {
      color: white !important;
   }
</style>


<div class="container">
   <div class="span-12 prepend-5">
      <span style="font-size: 160px; font-weight: bold">404</span>
      <h2><?php echo $this->message ?></h2>
   </div>
</div>

<div class="container">
   <div class="span-4 inicio">
      <h3><?php echo $this->translate('Home') ?></h3>
      <hr/>
      <a href="/"><?php echo $this->translate('Click here to go back to the home page.') ?></a>
   </div>
   <div class="span-4 prepend-1 programacao">
      <h3><?php echo $this->translate('Schedule') ?></h3>
      <hr/>
      <a href="<?= $this->url(array(), 'programacao', true) ?>">
         <?php echo $this->translate('Check the schedule of the conference which has Lectures, Mini courses and Workshops.') ?></a>
   </div>
   <div class="span-4 prepend-1 login">
      <h3><?php echo $this->translate('Login') ?></h3>
      <hr/>
      <a href="<?= $this->url(array(), 'login', true) ?>">
          <?php echo $this->translate('Login on SiGE to have access to your page of interest, paper submission, etc.') ?>
       </a>
   </div>
   <div class="span-4 prepend-1 participar">
      <h3><?php echo $this->translate('Get Involved') ?></h3>
      <hr/>
      <a href="<?= $this->url(array(), 'participar', true) ?>">
          <?php echo $this->translate('Join us and get involved in the conference. To do that just sign up and bring 1Kg of food on the conference day.') ?>
       </a>
   </div>
</div>

<?php if (isset($this->exception)): ?>

   <h3>Exception information:</h3>
   <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
   </p>

   <h3>Stack trace:</h3>
   <pre><?php echo $this->exception->getTraceAsString() ?>
   </pre>

   <h3>Request Parameters:</h3>
   <pre><?php echo var_export($this->request->getParams(), true) ?>
   </pre>
<?php endif; ?>
