<style>
  pre.stack-trace {
      white-space: pre-wrap;       /* CSS 3 */
      white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
      white-space: -pre-wrap;      /* Opera 4-6 */
      white-space: -o-pre-wrap;    /* Opera 7 */
      word-wrap: break-word;       /* Internet Explorer 5.5+ */
  }
</style>

<h1><?php echo $this->translate('An error occurred') ?></h1>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>

<h3><?php echo $this->translate('Exception information:') ?></h3>
<p>
  <b><?php echo $this->translate('Message:') ?></b> <?php echo $this->exception->getMessage() ?>
</p>

<h3>Stack trace:</h3>
<pre class="stack-trace"><?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Request Parameters:</h3>
<pre><?php echo var_export($this->request->getParams(), true) ?>
</pre>
<?php endif ?>
