
<div style="margin-top: 10px;">
   <ul data-role="listview" data-filter="true" data-filter-placeholder="Buscar eventos..." data-inset="true">
      <?php foreach ( $this->listaParticipanteEventoTabela as $item ): ?>
      <li>
         <h2>
            <?php echo $item["nome_tipo_evento"];?>: <?php echo $item["nome_evento"];?>
         </h2>
         <?php $date = new Zend_Date($item["data"]); ?>
         <p style="font-size: 12pt;">
         <?=$date->toString('dd MMM') ?> -
         <?php echo $item["hora_inicio"];?> as <?php echo $item["hora_fim"];?>
         </p>
         <p style="font-size: 11pt;">Sala: <?=$item['nome_sala'] ?></p>
         <?php if (!$item['validada']): ?>
         <p><i class="icon-warning-sign"></i> Este evento foi invalidado e pode não ser ministrado.</p>
         <?php endif; ?>
      </li>
      <?php endforeach; ?>
   </ul>
</div>