<style id="combined-heading-and-section">
   .custom-corners {
      box-shadow: 2px 2px 3px #ddd;
      margin-bottom: 6px;
   }
   .custom-corners .ui-bar {
      -webkit-border-top-left-radius: inherit;
      border-top-left-radius: inherit;
      -webkit-border-top-right-radius: inherit;
      border-top-right-radius: inherit;
   }
   .custom-corners .ui-body {
      border-top-width: 0;
      -webkit-border-bottom-left-radius: inherit;
      border-bottom-left-radius: inherit;
      -webkit-border-bottom-right-radius: inherit;
      border-bottom-right-radius: inherit;
   }
</style>

<h3 class="ui-bar ui-bar-a ui-corner-all" style="margin-top: -5px;">Eventos do meu interesse</h3>

<form>
   <input data-type="search" id="interesses" placeholder="Buscar eventos..." data-clear-btn="true">
</form>
<div class="elements" data-filter="true" data-input="#interesses">
   <?php foreach ($this->listaParticipanteEventoTabela as $item): ?>
      <div class="ui-corner-all custom-corners">
         <div class="ui-bar ui-bar-a">
            <h3>
               <?php echo $item["nome_tipo_evento"]; ?>: <?php echo $item["nome_evento"]; ?>
            </h3>
         </div>
         <div class="ui-body ui-body-a">
            <?php $date = new Zend_Date($item["data"]); ?>
            <p style="font-size: 12pt;">
               <?php echo $date->toString("dd 'de' MMM") ?> -
               <?php echo $item["hora_inicio"]; ?> as <?php echo $item["hora_fim"]; ?>
            </p>
            <p style="font-size: 11pt;">Local: <?php echo $item['nome_sala'] ?></p>
            <?php if (!$item['validada']): ?>
               <p><i class="icon-warning-sign"></i> Este evento foi invalidado e pode não ser ministrado.</p>
            <?php endif; ?>
            <a href="<?php echo $this->url(array('id' => $item['id_evento']),
                    'mobile_ver_evento', true); ?>#disqus_thread"
               data-ajax="false"
               class="ui-btn ui-shadow ui-corner-all ui-mini">
               <i class="icon-comments-alt"></i> Comentários
            </a>
         </div>
      </div>
   <?php endforeach; ?>
</div>
