<?php
   $this->headScript()
        ->prependFile($this->baseUrl('js/admin/horario/salvar.js'), 'text/javascript')
        ->prependFile($this->baseUrl('js/jquery.dataTables.js'))
        ->prependFile($this->baseUrl('js/jquery-1.6.2.min.js'));
   
   $this->headLink()
           ->appendStylesheet($this->baseUrl('css/screen.css'))
           ->appendStylesheet($this->baseUrl('css/form.css'))
           ->appendStylesheet($this->baseUrl('css/tabela_sort.css'));
?>

<a href="<?=$this->url(array('module' => 'admin',
    'controller' => 'evento',
    'action' => 'detalhes',
    'id' => $this->idEvento), 'default', true) ?>"
    class="no-bottom"><i class="icon-reply"></i> Voltar</a>

<h2>Novo horário</h2>

<?php
echo $this->form;
?>

<hr/>

<h4>Outros Horários</h4>
<table class="display" cellpadding="0" cellspacing="0" border="0;" >
   <thead>
      <tr>
         <th>Data</th>
         <th>Hora Início</th>
         <th>Hora Fim</th>

      </tr>
   </thead>
   <tbody>
      <?php foreach ($this->horariosEventos as $horario): ?>
         <tr>
            <td><?php echo $horario["data"] ?></td>
            <td><?php echo $horario["hora_inicio"] ?></td>
            <td><?php echo $horario["hora_fim"] ?></td>
         </tr>
      <?php endforeach; ?>
   </tbody>
</table>
