<?php
    $this->headScript()->appendFile($this->baseUrl('js/admin/horario/salvar.js'));
?>

<?php
$form = $this->form;
?>

<form method="<?php echo $form->getMethod() ?>" action="<?php echo
$form->getAction()?>">

<div class="row">
    <div class="col-md-6">

        <div class="box box-solid">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $form->descricao->renderLabel() ?>
                        <div class="form-group">
                            <?php echo $form->descricao->renderViewHelper() ?>
                            <div class="form-errors">
                                <?php echo $form->descricao->renderErrors() ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <?php echo $form->id_sala->renderLabel() ?>
                        <div class="form-group">
                            <?php echo $form->id_sala->renderViewHelper() ?>
                            <div class="form-errors">
                                <?php echo $form->id_sala->renderErrors() ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        <?php echo $form->data->renderLabel() ?>
                        <div class="form-group">
                            <div class="radio">
                                <?php echo $form->data->renderViewHelper() ?>
                            </div>
                        </div>
                        <div class="form-errors">
                            <?php echo $form->data->renderErrors() ?>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <?php echo $form->hora_inicio->renderLabel() ?>
                        <div class="form-group">
                            <?php echo $form->hora_inicio->renderViewHelper() ?>
                            <div class="form-errors">
                                <?php echo $form->hora_inicio->renderErrors() ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <?php echo $form->hora_fim->renderLabel() ?>
                        <div class="form-group">
                            <?php echo $form->hora_fim->renderViewHelper() ?>
                            <div class="form-errors">
                                <?php echo $form->hora_fim->renderErrors() ?>
                            </div>
                        </div>
                    </div>
                </div>

                <hr>

                <div class="row">
                    <div class="col-md-12">
                        <a href="<?=$this->url(array('module' => 'admin',
                            'controller' => 'evento',
                            'action' => 'detalhes',
                            'id' => $this->idEvento), 'default', true) ?>"
                            class="btn btn-default">
                            <i class="fa fa-chevron-left"></i> <?php echo $this->translate("Back"); ?>
                        </a>
                        <?php echo $form->submit->renderViewHelper() ?>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="col-md-6">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Outros Horários</h3>
            </div>
            <div class="box-body no-padding">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Descrição</th>
                            <th>Data</th>
                            <th>Hora Início</th>
                            <th>Hora Fim</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->horariosEventos as $horario): ?>
                            <tr>
                                <td><?php echo $horario["descricao"] ?></td>
                                <td><?php echo $horario["data"] ?></td>
                                <td><?php echo $horario["hora_inicio"] ?></td>
                                <td><?php echo $horario["hora_fim"] ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

</form>

<hr/>
