<?php
    $this->headScript()->appendFile($this->baseUrl('js/select2.js'));
    $this->headScript()->appendFile($this->baseUrl('js/parsley.i18n/messages.pt_br.js'));
    $this->headScript()->appendFile($this->baseUrl('js/parsley.min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/jquery.maskedinput.min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/participante/criar.js'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/form.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/select2.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/participante/criar.css'));
?>

<a href="<?=$this->url(array(), 'login', true) ?>"
      class="no-bottom"><i class="icon-signin"></i> <?php echo $this->translate("Login"); ?></a>
<?php
    echo $this->form;
?>
<br/><br/><font color="#828282">* <?php echo $this->translate("Required fields"); ?></font>
