<?php
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/select2/select2.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/select2/select2-bootstrap.css'));

    $this->headScript()->appendFile($this->baseUrl('lib/js/parsley/i18n/messages.pt_br.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/parsley/parsley.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/select2/select2.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/select2/select2_locale_pt-BR.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/maskedinput/jquery.maskedinput.min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/participante/editar.js'));
?>

<ul class="nav nav-pills">
    <li>
        <a href="<?php echo $this->url(array('controller' => 'participante',
                    'action' => 'ver'), 'default', true); ?>">
            <i class='icon-user'></i>
            <?php echo sprintf($this->translate("%s's page"), $this->user->nome); ?>
        </a>
    </li>
    <li class="active">
        <a href="<?php echo $this->url(array('controller'=>'participante',
         'action'=>'editar'), 'default', true);?>">
            <i class='icon-edit'></i>
            <?php echo $this->translate("Edit"); ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('controller'=>'participante',
         'action'=>'alterar-senha'), 'default', true);?>">
            <i class='icon-lock'></i>
            <?php echo $this->translate("Alter Password"); ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('controller'=>'participante',
         'action'=>'certificados'), 'default', true);?>">
            <i class='icon-credit-card'></i>
            <?php echo $this->translate("Certificates"); ?>
        </a>
    </li>
</ul>

<hr>

<div class="row">
    <div class="col-md-9">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li class="active">
                <a href="#tab-1" role="tab" data-toggle="tab">
                    <?php echo $this->translate("Profile"); ?>
                </a>
            </li>
            <li>
                <a href="#tab-2" role="tab" data-toggle="tab">
                    <?php echo $this->translate("Social Networks"); ?>
                </a>
            </li>
        </ul>
    </div>
    <div class="col-md-3">
        <a href="<?php echo $this->url(array(
                    'controller' => 'participante',
                    'action' => 'ticket'
                ), 'default', true) ?>" class="btn btn-primary btn-lg btn-block">
            <i class="fa fa-cloud-download"></i>
            Baixar Ticket de Inscrição
        </a>
    </div>
</div>

<?php
$form = $this->form;
?>

<form method="<?php echo $form->getMethod() ?>"
    action="<?php echo $form->getAction()?>"
    data-validate="parsley">
    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active" id="tab-1">
            <?php echo $this->partial('partials/participante/editar/tab-1.phtml', array('form' => $form)); ?>
        </div>
        <div class="tab-pane" id="tab-2">
            <?php echo $this->partial('partials/participante/editar/tab-2.phtml', array('form' => $form)); ?>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-6">
            <a href="<?php echo $this->url(array(
                'controller' => 'participante',
                'action' => 'ver'), 'default', true)?>" class="btn btn-default">
            <?php echo $this->translate("Cancel"); ?>
        </a>
            <?php echo $form->submit->renderViewHelper() ?>
        </div>
    </div>
</form>
