<?php
    //$this->headLink()->appendStylesheet($this->baseUrl('css/tabela_sort.css'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/bootstrap/bootbox.min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/participante/index.js'));
?>

<style>
    .panel-title {
        line-height: 1.4;
    }
</style>

<div class="row">
    <div class="col-md-6">
        <h3><?php echo $this->translate("Interest List"); ?></h3>
    </div>
    <div class="col-md-6">
        <a href="<?=$this->url(array('controller' => 'evento',
                 'action' => 'interesse')) ?>" class="btn btn-primary btn-lg pull-right">
            <i class="fa fa-plus"></i>
            <?php echo $this->translate("Events of Interest"); ?>
        </a>
    </div>
</div>

<hr>

<?php if (empty($this->listaParticipanteEventoTabela)): ?>
    <div class="alert alert-info">
        <?php echo $this->translate("You don't have any events added. Click in 'Events of Interest' and browse to see date, time and place of events of interest."); ?>
    </div>
<?php else: ?>
    <div class="row">
    <?php foreach ($this->listaParticipanteEventoTabela as $item): ?>
        <?php
            $css_painel_type = "panel-default";
            if (!$item['validada']) {
                $css_painel_type = "panel-warning";
            }
        ?>
        <div class="col-md-4" id="panel_event_<?php echo $item["evento"]; ?>">
            <div class="panel <?php echo $css_painel_type; ?>">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="label label-primary"><?php echo $item["nome_tipo_evento"];?></span>
                        <?php echo $item["nome_evento"];?>
                        <?php /* <?=$this->url(array(
                           'controller' => 'evento',
                           'action' => 'desfazer-interesse',
                           'id' => $item["evento"])) ?> */ ?>
                        <a href="#" onclick="return false;"
                            class="close pull-right"
                            data-id-evento="<?php echo $item["evento"]; ?>"
                            data-toggle="tooltip" data-placement="top"
                            title="<?php echo $this->translate("Remove"); ?>">
                           <span aria-hidden="true">&times;</span>
                           <span class="sr-only">Close</span>
                        </a>
                    </h3>
                </div>
                <div class="panel-body">
                    <div>
                        <?php echo $this->translate("Date"); ?>:
                        <?php echo $item["data"];?>
                    </div>
                    <div>
                        <?php echo $this->translate("Time"); ?>:
                        <?php echo $item["hora_inicio"];?> - <?php echo $item["hora_fim"];?>
                    </div>
                    <div>
                        <?php echo $this->translate("Place"); ?>:
                        <?php echo $item["data"];?>
                        <?php echo $item["nome_sala"];?>
                    </div>

                    <?php if (!$item['validada']): ?>
                    <div class="text-warning">
                        <i class="fa fa-warning"></i>
                        <?php echo $this->translate("This event was invalidated and could not be given."); ?>
                    </div>
                    <?php endif; ?>

                </div>
            </div>
        </div>
    <?php endforeach; ?>
    </div>
<?php endif; ?>
