
<fieldset>
    <legend><?php echo $this->translate("Interest List"); ?></legend>
    <a style="float:right; clear:right;"
			href="<?=$this->url(array('controller' => 'evento',
             'action' => 'interesse')) ?>" class="no-bottom">
		<i class="icon-plus"></i> <?php echo $this->translate("View and add events of your interest"); ?>
	</a>
	<table class="display" cellpadding="0" cellspacing="0" border="0">
		<thead>
			<tr>
				<th><?php echo $this->translate("Description"); ?></th>
				<th><?php echo $this->translate("Date"); ?></th>
				<th><?php echo $this->translate("Time"); ?></th>
				<th><?php echo $this->translate("Place"); ?></th>
				<td style="width: 90px;">&nbsp;</td>
			</tr>
		</thead>
		<tbody>
		<?php foreach ( $this->listaParticipanteEventoTabela as $item ): ?>
			<tr>
				<td>
               <?php if (!$item['validada']): ?>
                  <i class="icon-warning-sign"
                     title="<?php echo $this->translate("This event was invalidated and could not be given."); ?>"></i>
               <?php endif; ?>
               <?php echo $item["nome_tipo_evento"];?> -
               <?php echo $item["nome_evento"];?>
            </td>
				<td><?php echo $item["data"];?></td>
				<td><?php echo $item["hora_inicio"];?> - <?php echo $item["hora_fim"];?></td>
				<td><?php echo $item["nome_sala"];?></td>
				<td>
					<a href="<?=$this->url(array(
                   'controller' => 'evento',
                   'action' => 'desfazer-interesse',
                   'id' => $item["evento"])) ?>" class="no-bottom">
                  <i class="icon-reply"></i> Desfazer</a>
				</td>
		  </tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</fieldset>
