
<div class="success">
   <h3><?php echo $this->translate("Signup successfully performed, verify you e-mail!"); ?></h3>
   <p><?php echo $this->translate("There you will find your default password. Your login will be your e-mail address."); ?></p>
</div>

<p>
	<?php echo $this->translate(_("Then you just need to")); ?>
    <a href="<?=$this->url(array(),
        'login', true) ?>" class="no-bottom">
        <i class="icon-signin"></i> <?php echo $this->translate("Login"); ?>
    </a>.
</p>