
<?php if (! empty($this->user)): ?>
<ul class="nav nav-pills">
    <?php if ($this->mostrarEditar): ?>
    <li class="active">
        <a href="<?php echo $this->url(array('controller' => 'participante',
                    'action' => 'ver'), 'default', true); ?>">
            <i class='icon-user'></i>
            <?php echo sprintf($this->translate("%s's page"), $this->user->nome); ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('controller'=>'participante',
         'action'=>'editar'), 'default', true);?>">
            <i class='icon-edit'></i>
            <?php echo $this->translate("Edit"); ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('controller'=>'participante',
         'action'=>'alterar-senha'), 'default', true);?>">
            <i class='icon-lock'></i>
            <?php echo $this->translate("Alter Password"); ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('controller'=>'participante',
         'action'=>'certificados'), 'default', true);?>">
            <i class='icon-credit-card'></i>
            <?php echo $this->translate("Certificates"); ?>
        </a>
    </li>
    <?php else: ?>
    <li class="active">
        <a href="<?=$this->url(array('id' => $this->id),
        'ver') ?>">
            <i class='icon-user'></i>
            <?php echo sprintf($this->translate("%s's page"), $this->user->nome); ?>
        </a>
    </li>
    <?php endif; ?>
</ul>

<hr>

<div class="row">
    <div class="col-md-3">
        <div class="thumbnail">
            <?php
            // hash for gravatar
            $hash = md5(strtolower(trim($this->user->email)));
            ?>
            <img src="http://www.gravatar.com/avatar/<?php echo $hash; ?>?s=172&d=retro"
                alt="profile-image" />
            <div class="caption">
                <p>
                    <?php echo $this->translate("SiGE uses Gravatar for profile avatar."); ?>
                </p>
                <p>
                    <a href="https://signup.wordpress.com/signup/?ref=oauth2&oauth2_redirect=f941fb72fe145f66fde68102b63b8802%40https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3D829a6f7bbbb5c9da810d10bf289a6b85c8be54ddd9b8cbe323e4a383e2278c21%26redirect_uri%3Dhttps%253A%252F%252Fen.gravatar.com%252Fconnect%252F%253Faction%253Drequest_access_token%26jetpack-code%26jetpack-user-id%3D0%26action%3Doauth2-login&wpcom_connect=1"
                        class="btn btn-primary btn-sm btn-block"
                        target="_blank">
                        <?php echo $this->translate("Configure Gravatar"); ?>
                    </a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                <?php echo $this->translate("About me:"); ?>
            </div>
            <div class="panel-body">
                <?php if(! empty($this->user->bio)): ?>
                    <?php echo $this->user->bio; ?>
                <?php else: ?>
                    <span class="text-muted">
                        <?php echo $this->translate("No description yet..."); ?>
                    </span>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-md-1">
        <?php echo $this->partial('partials/participante/ver/twitter-button.phtml', array(
           'id' => $this->id,
           'user' => $this->user
        )); ?>
    </div>
    <div class="col-md-1">
        <?php echo $this->partial('partials/participante/ver/facebook-button.phtml', array(
            'id' => $this->id,
        )); ?>
    </div>
    <div class="col-md-1">
        <?php echo $this->partial('partials/participante/ver/gplus-button.phtml', array(
            'id' => $this->id,
        )); ?>
    </div>
</div>

<?php
// HACK: usuários não devem ter @ no username do twitter, é um caractere implicito
// ao invés disso ele deve ser usado concatenando o @
// DONE: remover todos os @ de usuários da base de dados antes de remover este HACK!
$tw_user = str_replace("@", "", $this->user->twitter);
if (! empty($tw_user)) {
   $twitter = sprintf($this->translate("Follow me on %s"),
        '<a href="https://twitter.com/#!/' . $tw_user . '" class="btn btn-primary" target="_blank"><i class="fa fa-twitter"></i> Twitter</a>');
} else {
   $twitter = sprintf($this->translate("I still don't have %s"),
        '<a href="https://twitter.com" class="btn btn-primary" target="_blank"><i class="fa fa-twitter"></i> Twitter</a>');
}
?>
<div class="row">
    <div class="col-md-6">
        <p><?=$twitter ?></p>
    </div>
    <div class="col-md-6">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-default dropdown-toggle"
                data-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-cog"></i>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="<?php echo $this->url(array(
                    'controller' => 'participante',
                    'action' => 'ticket'
                ), 'default', true) ?>">2° via do Ticket de Inscrição</a></li>
            </ul>
        </div>
    </div>
</div>


    <?php if (!is_null($this->slides)): ?>
    <hr/>
    <div class="row">
        <div class="col-md-12">
            <a href="http://slideshare.net" target="_blank">
             <img src="<?php echo $this->baseUrl('img/slideshare_200x50.png'); ?>"/>
          </a>
        </div>
        <div class="col-md-12">
            <h4 style="padding-top: 6px;"><?php echo $this->translate("Slideshows of"); ?>
             <a href="http://slideshare.net/<?php echo $this->user->slideshare ?>" target="_blank">
                <?php echo $this->user->slideshare ?>
             </a>
          </h4>
        </div>
        <hr/>
    </div>

    <?php
        $maxEmbedSlides = 4;
        $i = 0;
    ?>

    <div class="row">
    <?php foreach ($this->slides as $item): ?>
       <div class="col-md-6">
            <?php if ($i < $maxEmbedSlides): ?>
                <?php echo ($item->getEmbedCode()); ?>
            <?php else: ?>
                <i class='fa fa-external-link'></i>
                <a href="<?php echo $item->getPermaLink(); ?>" target="_blank">
                <?php echo $item->getTitle(); ?></a>
            <?php endif; ?>
       </div>

    <?php
            $i++;
        endforeach;
    ?>
    </div><!-- end of .row -->

    <?php else: // else: slides not null ?>
    <p>
        <?php echo $this->translate("Create an account on"); ?>
        <a href="http://www.slideshare.net/" target="_blank">
            <i class="fa fa-slideshare"></i>
            Slideshare
        </a>
        <?php echo $this->translate("so your presentations can appear here."); ?>
    </p>
    <?php endif; // end: slides not null ?>

<?php else: // else: not empty user ?>
    <div class="alert alert-warning"><?php echo $this->translate("Participant not found."); ?></div>
<?php endif; // end: not empty user ?>

<?php if (isset($this->slideshareError)): ?>
<div class="alert alert-warning" role="alert">
    <strong><?php echo $this->translate("Attention!"); ?></strong>
    <div>
        <?php echo $this->translate("Slideshare user"); ?>
        <strong><?php echo $this->user->slideshare; ?></strong>
        <?php echo $this->translate("not found."); ?>
    </div>
    <div>
        <?php echo $this->translate("Details:"); ?>
        <?php echo $this->slideshareError; ?>
    </div>
</div>
<?php endif; ?>
