
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-3 column">
        <h4>SiGE</h4>
        <ul class="nav">
            <li>
                <a href="<?php echo $this->url(array(), 'sobre', true) ?>">
                    <?php echo $this->translate("About"); ?>
                </a>
            </li>
            <li>
                <a href="https://github.com/comsolid/sige" target="_blank">
                    <i class="fa fa-github"></i>
                    <?php echo $this->translate("Source Code on Github"); ?>
                </a>
            </li>
            <li>
                <a href="http://comsolid.org" target="_blank">
                    <i class="fa fa-globe"></i>
                    COMSOLiD
                </a>
            </li>
        </ul>
    </div>

    <div class="col-xs-6 col-sm-6 col-md-3 col-md-offset-6 column">
        <!-- Your Team -->
        <h4>Your Team</h4>
        <ul class="nav">
            <li>
                <a href="#">
                    <i class="fa fa-globe"></i>
                    Website
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-twitter"></i>
                    Twitter
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-facebook"></i>
                    Facebook
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-google-plus"></i>
                    Google Plus
                </a>
            </li>
        </ul>
    </div>

</div>
