<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sistema de Gerência de Eventos">
    <meta name="author" content="COMSOLiD -  Comunidade Maracanauense de Software Livre e Inclusão Digital">
    <link rel="icon" href="<?php echo $this->baseUrl('imagens/layout/favicon_sige.png'); ?>">

    <title>SiGE | COMSOLiD</title>
    <?php
        $this->headLink()->appendStylesheet($this->baseUrl('css/sigecss.css'));
        $this->headLink()->prependStylesheet($this->baseUrl('lib/css/font-awesome/font-awesome.min.css'));
        $this->headLink()->prependStylesheet($this->baseUrl('lib/css/bootstrap/navbar-fixed-top.css'));
        $this->headLink()->prependStylesheet($this->baseUrl('lib/css/bootstrap/default/bootstrap.min.css'));
    ?>

    <?php
        $this->headScript()->prependFile($this->baseUrl('js/utils.js'));
        $this->headScript()->prependFile($this->baseUrl('js/jed/jed-init.js'));
        $this->headScript()->prependFile($this->baseUrl('js/jed/locale/pt_BR.js'));
        $this->headScript()->prependFile($this->baseUrl('js/jed/jed.js'));
        $this->headScript()->prependFile($this->baseUrl('lib/js/bootstrap/bootstrap.min.js'));
        $this->headScript()->prependFile($this->baseUrl('js/jquery-1.10.2.min.js'));
    ?>

    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,500">
    <style>
        body {
            font-family: 'Source Sans Pro', "Helvetica Neue", Helvetica, Arial;
            font-size: 15px;
        }
    </style>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- HINT: REMOVE ME IN PRODUCTION! -->
    <script src="http://localhost:35729/livereload.js"></script>
</head>

<body>
    <?php $usuario = Zend_Auth::getInstance()->getIdentity(); ?>
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span class="navbar-brand">COMSOLiD</span>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <?php echo (is_object($this->menu)) ? $this->menu->getView() : ""; ?>
                </ul>
                <?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'participante',
                    'action' => 'ver'), 'default', true); ?>">
                            <i class="fa fa-user"></i>
                            <?= $usuario[ 'apelido'] ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array(), 'logout', true); ?>">
                            <i class="fa fa-sign-out"></i>
                            <?php echo $this->translate("Logout"); ?>
                        </a>
                    </li>
                </ul>
                <?php else: ?>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="<?php echo $this->url(array(), 'login', true); ?>">
                                <i class="fa fa-sign-in"></i>
                                <?php echo $this->translate("Login"); ?>
                            </a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>

    <div id="master-container" class="container">

        <?php echo $this->flashMessages(); ?>
        <?php echo $this->layout()->content; ?>

    </div>
    <!-- /container -->

    <footer id="footer">
        <div class="container">
            <?php echo $this->render('twbs3/footer.phtml'); ?>
        </div>
    </footer>

    <?php echo $this->headScript(); ?>
</body>

</html>
