<?php echo $this->partial('menu.phtml'); ?>

<br>
<input type="text" class="text" name="termo" id="termo"
       placeholder="Buscar caravana..." size="50" style="float: left;" />
<img id="loading" src="<?=$this->baseUrl('img/loading.gif') ?>"
     style="display: none; float: left;" />

<table class="display" cellpadding="0" cellspacing="0" border="0">
   <thead>
      <tr>
         <th>Nome</th>
         <th>Apelido</th>
         <th>Responsável</th>
         <th>Municipio</th>
         <th>Instituição</th>
         <th>Válida</th>
         <th>Inscritos</th>
         <th>Validar</th>
         <th>Invalidar</th>
      </tr>
   </thead>
   <tbody id="resultadoCaravana">
   </tbody>
</table>