
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate("Current Conference"); ?></h3>
            </div>
            <div class="list-group">
                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-por-dia'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-calendar"></i>
                    <?php echo $this->translate("Registrations per day"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-horario'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-clock-o"></i>
                    <?php echo $this->translate("Registrations per hour of day"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-sexo'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-user"></i>
                    <?php echo $this->translate("Registrations per gender"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-municipio-15-mais'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-flag"></i>
                    <?php echo $this->translate("Registrations per district (15+)"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-municipio'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-flag"></i>
                    <?php echo $this->translate("Registrations per district (All)"); ?>
                </a>
            </div>
        </div>
    </div>
</div>
