
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate("Graphs"); ?></h3>
            </div>
            <div class="list-group">
                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-por-dia'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-calendar"></i>
                    <?php echo $this->translate("Registrations per day"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-horario'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-clock-o"></i>
                    <?php echo $this->translate("Registrations per hour of day"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-sexo'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-user"></i>
                    <?php echo $this->translate("Registrations per gender"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-municipio-15-mais'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-flag"></i>
                    <?php echo $this->translate("Registrations per district (15+)"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-municipio'), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-flag"></i>
                    <?php echo $this->translate("Registrations per district (All)"); ?>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate("Reports"); ?></h3>
            </div>
            <div class="list-group">

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-lista-pdf',
                    "id_encontro" => $this->id_encontro,
                    "status" => "todas"), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-file-pdf-o"></i>
                    <?php echo $this->translate("Todas as inscrições (PDF)"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-lista-xls',
                    "id_encontro" => $this->id_encontro,
                    "status" => "todas"), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-file-excel-o"></i>
                    <?php echo $this->translate("Todas as inscrições (XLS)"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-lista-pdf',
                    "id_encontro" => $this->id_encontro,
                    "status" => "nao-confirmadas"), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-file-pdf-o"></i>
                    <?php echo $this->translate("Inscrições não confirmadas"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-lista-pdf',
                    "id_encontro" => $this->id_encontro,
                    "status" => "confirmadas"), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-file-pdf-o"></i>
                    <?php echo $this->translate("Inscrições confirmadas"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'artigos-lista-pdf',
                    'ano' => date('Y')), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-file-pdf-o"></i>
                    <?php echo $this->translate("Lista de artigos submetidos (PDF)"); ?>
                </a>

                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'artigos-lista-xls',
                    'ano' => date('Y')), 'default', true); ?>"
                    class="list-group-item">
                    <i class="fa fa-file-excel-o"></i>
                    <?php echo $this->translate("Lista de artigos submetidos (XLS)"); ?>
                </a>

            </div>
        </div>
    </div>
</div>
