<?php echo $this->partial('menu.phtml'); ?>

<div class="container">
    <div class="span-8 prepend-1">
        <h3><?php echo $this->translate("Current Conference"); ?></h3><hr/>
        <ul class="unstyled">
            <li>
                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-por-dia'), 'default', true); ?>"
                   class="no-bottom">
                    <i class="icon-calendar"></i>
                    <?php echo $this->translate("Registrations per day"); ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array(
                       'module' => 'admin',
                       'controller' => 'relatorios',
                       'action' => 'inscricoes-horario'), 'default', true); ?>"
                   class="no-bottom">
                    <i class="icon-time"></i>
                    <?php echo $this->translate("Registrations per hour of day"); ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array(
                       'module' => 'admin',
                       'controller' => 'relatorios',
                       'action' => 'inscricoes-sexo'), 'default', true); ?>"
                   class="no-bottom">
                    <i class="icon-user"></i>
                    <?php echo $this->translate("Registrations per gender"); ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-municipio-15-mais'), 'default', true); ?>"
                   class="no-bottom">
                    <i class="icon-flag"></i>
                    <?php echo $this->translate("Registrations per district (15+)"); ?>
                </a>
            </li>
            <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'relatorios',
                    'action' => 'inscricoes-municipio'), 'default', true); ?>"
                   class="no-bottom">
                    <i class="icon-flag"></i>
                    <?php echo $this->translate("Registrations per district (All)"); ?>
                </a>
            </li>
        </ul>
    </div>
</div>
