<?php
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/morris/morris.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/alertifyjs/alertify.min.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('lib/css/alertifyjs/themes/bootstrap.min.css'));

    $this->headScript()->appendFile($this->baseUrl('lib/js/morris/raphael-min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/morris/morris.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/sprintfjs/sprintf.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/alertifyjs/alertify.min.js'));
    $this->headScript()->appendFile($this->baseUrl('lib/js/alertifyjs/alertify.override.js'));
    $this->headScript()->appendFile($this->baseUrl('js/admin/relatorio/relatorio-utils.js'));
    $this->headScript()->appendFile($this->baseUrl('js/admin/relatorio/inscricoes-municipio-15-mais.js'));
?>

<div class="row">
    <div class="col-md-9 col-md-offset-1">
        <div class="box box-solid box-primary">
            <div class="box-header">
                <div class="box-tools pull-right">
                    <div class="btn-group">
                        <button id="reload" class="btn btn-primary">
                            <i class="fa fa-refresh"></i> <?php echo $this->translate("Reload"); ?>
                        </button>
                    </div>
                </div>
            </div>
            <div class="box-body">
                <div id="bar-chart" style="width: 100%;"></div>
            </div>
        </div>
    </div>
</div>
