<?php
    $this->headLink()->appendStylesheet($this->baseUrl('css/screen.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/morris.css'));

    $this->headScript()->appendFile($this->baseUrl('js/raphael-min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/morris.min.js'));
    $this->headScript()->appendFile($this->baseUrl('js/sprintf-0.6.js'));
    $this->headScript()->appendFile($this->baseUrl('js/admin/relatorio/relatorio-utils.js'));
    $this->headScript()->appendFile($this->baseUrl('js/admin/relatorio/inscricoes-por-dia.js'));
    echo $this->partial('menu.phtml');
?>

<div class="error" style="display: none;margin-top: 10px;"></div>
<div class="container">
   <div class="span-14">
      <h3><?php echo $this->translate("Registrations per day"); ?></h3>
   </div>
   <div class="span-4">
      <a id="reload" href="#" class="no-bottom" onclick="return false;">
         <i class="icon-refresh"></i> <?php echo $this->translate("Reload"); ?>
      </a>
   </div>
</div>
<hr/>
<div id="line-chart" style="width: 800px;"></div>
