<!-- BEGIN : botão curtir do facebook -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=336256479809348";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- END : botão curtir do facebook -->

<!-- facebook button -->
<div class="fb-like" data-href="<?=$this->serverUrl() . $this->url(array('id' => $this->id),
     'ver', true) ?>" data-send="false" data-layout="button_count"
     data-width="450" data-show-faces="false"></div>
