<!-- twitter button -->
<?php $config = new Zend_Config_Ini(APPLICATION_PATH . '/configs/application.ini', 'staging'); ?>
<a href="https://twitter.com/share" class="twitter-share-button"
   data-url="<?=$this->serverUrl() . $this->url(array('id' => $this->id),
     'ver', true) ?>"
     data-text="Página de <?=$this->user->nome ?>"
     data-via="<?=$config->twitter->username ?>"
     data-lang="pt" data-hashtags="<?=$config->twitter->hashtags ?>">Tweetar</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
