<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>SiGE | COMSOLiD</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link rel="icon" href="<?php echo $this->baseUrl('img/favicon.ico'); ?>">
    <?php
        $this->headLink()->prependStylesheet($this->baseUrl('lib/css/bootstrap-admin/all-skins.min.css'));
        $this->headLink()->prependStylesheet($this->baseUrl('lib/css/bootstrap-admin/AdminLTE.min.css'));
        $this->headLink()->prependStylesheet($this->baseUrl('lib/css/font-awesome/font-awesome.min.css'));
        $this->headLink()->prependStylesheet($this->baseUrl('lib/css/bootstrap/default/bootstrap.min.css'));
    ?>

    <?php
        $this->headScript()->prependFile($this->baseUrl('js/utils.js'));
        $this->headScript()->prependFile($this->baseUrl('js/jed/jed-init.js'));
        $this->headScript()->prependFile($this->baseUrl('js/jed/locale/pt_BR.js'));
        $this->headScript()->prependFile($this->baseUrl('js/jed/jed.js'));
        $this->headScript()->prependFile($this->baseUrl('lib/js/bootstrap-admin/app.js'));
        $this->headScript()->prependFile($this->baseUrl('lib/js/bootstrap-admin/fastclick.min.js'));
        $this->headScript()->prependFile($this->baseUrl('lib/js/bootstrap/bootstrap.min.js'));
        $this->headScript()->prependFile($this->baseUrl('lib/js/jquery/jquery-1.10.2.min.js'));
    ?>

    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>

    <!-- HINT: ENABLE ME IN DEVELOPMENT! -->
    <!--
    <script src="http://localhost:35729/livereload.js"></script>
    -->
</head>
<body class="skin-blue">

    <div class="wrapper">
        <!-- header logo: style can be found in header.less -->
        <header class="main-header">
            <a href="<?php echo $this->url(array(), 'admin', true); ?>" class="logo">
                <!-- Add the class icon to your logo image or logo icon to add the margining -->
                <img src="<?php echo $this->baseUrl('img/comsolid-admin-header.png'); ?>"
                    style="width: 200px;" alt="COMSOLiD" />
            </a>
            <?php echo $this->render('twbs3-admin/navbar-right.phtml') ?>
        </header>

        <!-- Left side column. contains the sidebar -->
        <?php echo $this->render('twbs3-admin/sidebar-left.phtml') ?>

        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    <?php echo (isset($this->title) ? $this->title : 'Blank page') ?>
                    <small><?php echo (isset($this->subtitle) ? $this->subtitle : 'Control panel') ?></small>
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <a href="<?php echo $this->url(array(), 'admin', true); ?>">
                            <i class="fa fa-dashboard"></i> <?php echo $this->translate('Dashboard'); ?>
                        </a>
                    </li>
                    <li class="active">
                        <?php echo (isset($this->title) ? $this->title : 'Blank page') ?>
                    </li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content" id="main-content">

                <?php echo $this->flashMessages(); ?>
                <?php echo $this->layout()->content; ?>

            </section><!-- /.content -->
        </div>

        <footer class="main-footer">
            <?php echo $this->render('twbs3-admin/footer.phtml'); ?>
        </footer>

    </div><!-- ./wrapper -->

    <?php echo $this->headScript(); ?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

</body>
</html>
