<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>SiGE | COMSOLiD</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <?php
        $this->headLink()->prependStylesheet($this->baseUrl('lib/css/bootstrap-admin/AdminLTE.css'));
        //$this->headLink()->appendStylesheet($this->baseUrl('css/sigecss.css'));
        $this->headLink()->prependStylesheet($this->baseUrl('lib/css/font-awesome/font-awesome.min.css'));
        //$this->headLink()->prependStylesheet($this->baseUrl('lib/css/bootstrap/navbar-fixed-top.css'));
        $this->headLink()->prependStylesheet($this->baseUrl('lib/css/bootstrap/default/bootstrap.min.css'));
    ?>
    <!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="//code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css" rel="stylesheet" type="text/css" /> -->

    <?php
        $this->headScript()->prependFile($this->baseUrl('js/utils.js'));
        $this->headScript()->prependFile($this->baseUrl('js/jed/jed-init.js'));
        $this->headScript()->prependFile($this->baseUrl('js/jed/locale/pt_BR.js'));
        $this->headScript()->prependFile($this->baseUrl('js/jed/jed.js'));
        $this->headScript()->prependFile($this->baseUrl('lib/js/bootstrap-admin/app.js'));
    ?>

    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body class="skin-black">
    <!-- header logo: style can be found in header.less -->
    <header class="header">
        <a href="<?php echo $this->url(array(), 'admin', true); ?>" class="logo">
            <!-- Add the class icon to your logo image or logo icon to add the margining -->
            SiGE
        </a>
        <?php echo $this->render('twbs3-admin/navbar-right.phtml') ?>
    </header>
    <div class="wrapper row-offcanvas row-offcanvas-left">
        <?php echo $this->render('twbs3-admin/sidebar-left.phtml') ?>

        <!-- Right side column. Contains the navbar and content of the page -->
        <aside class="right-side">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Blank page
                    <small>Control panel</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li class="active">Blank page</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">

                <?php echo $this->flashMessages(); ?>
                <?php echo $this->layout()->content; ?>

            </section><!-- /.content -->
        </aside><!-- /.right-side -->
    </div><!-- ./wrapper -->


    <!-- jQuery 2.0.2 -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
    <?php echo $this->headScript(); ?>

</body>
</html>
