
<?php $usuario = Zend_Auth::getInstance()->getIdentity(); ?>

<!-- Header Navbar: style can be found in header.less -->
<nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </a>
    <div class="navbar-right">
        <ul class="nav navbar-nav">
            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-user"></i>
                    <span><?php echo $usuario['apelido'] ?> <i class="caret"></i></span>
                </a>
                <ul class="dropdown-menu">
                    <!-- User image -->
                    <li class="user-header bg-light-blue">
                        <?php
                        $hash = md5(strtolower(trim($usuario['email'])));
                        ?>
                        <img src="http://www.gravatar.com/avatar/<?php echo $hash; ?>?s=172&d=retro" class="img-circle" alt="User Image" />
                        <p>
                            <?php echo $usuario['apelido'] ?>
                            <!--<small>Member since Nov. 2012</small>-->
                        </p>
                    </li>
                    <!-- Menu Body -->
                    <li class="user-body">
                        <div class="col-xs-6 text-center">
                            <a href="#">Followers</a>
                        </div>
                        <div class="col-xs-6 text-center">
                            <a href="#">Friends</a>
                        </div>
                    </li>
                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <div class="pull-left">
                            <a href="<?php echo $this->url(array(
                                    'controller' => 'participante',
                                    'action' => 'ver'
                                ), 'default', true); ?>" class="btn btn-default btn-flat">
                                <?php echo $this->translate("Profile"); ?>
                            </a>
                        </div>
                        <div class="pull-right">
                            <a href="<?php echo $this->url(array(), 'logout', true) ?>"
                                class="btn btn-default btn-flat">
                                <?php echo $this->translate("Logout"); ?>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>
