
<?php $usuario = Zend_Auth::getInstance()->getIdentity(); ?>

<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <?php
                $hash = md5(strtolower(trim($usuario['email'])));
                ?>
                <img src="http://www.gravatar.com/avatar/<?php echo $hash; ?>?s=172&d=retro" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p><?php echo $usuario['apelido'] ?></p>
            </div>
        </div>

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <?php echo (is_object($this->menu)) ? $this->menu->getView() : ""; ?>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>
