<?php
	$this->headLink()->appendStylesheet($this->baseUrl('lib/css/alertifyjs/alertify.min.css'));
	$this->headLink()->appendStylesheet($this->baseUrl('lib/css/alertifyjs/themes/bootstrap.min.css'));

	$this->headScript()->appendFile($this->baseUrl('lib/js/alertifyjs/alertify.min.js'));
	$this->headScript()->appendFile($this->baseUrl('lib/js/alertifyjs/alertify.override.js'));
	$this->headScript()->appendFile($this->baseUrl('lib/js/momentjs/moment-with-langs.min.js'));
	$this->headScript()->appendFile($this->baseUrl('lib/js/vue/vue.js'));
	$this->headScript()->appendFile($this->baseUrl('js/admin/participante/pre-inscricao.component.js'));
?>

<div id="pre-inscricao-app"></div>

<div class="alert alert-info">
	<h4><?php echo $this->translate("Information"); ?></h4>
	<p><?php echo $this->translate("This search brings only the first 20 best results."); ?></p>
</div>

<?php echo $this->partial('partials/participante/pre-inscricao/component.html'); ?>
<?php echo $this->partial('partials/participante/pre-inscricao/participante-busca.html'); ?>
<?php echo $this->partial('partials/participante/pre-inscricao/participante-lista.html'); ?>
<?php echo $this->partial('partials/participante/pre-inscricao/participante-item.html'); ?>
